### ISSUE TITLE
Repo error.

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado#1179]
I'm trying to install avocado follow the guide of http://avocado-framework.readthedocs.io/en/latest/GetStartedGuide.html

But I got this error.
https://repos-avocadoproject.rhcloud.com/static/fedora-1.1.1-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

Could you tell me how to fix this problem?

**Comment by clebergnu** [comment]
Our `avocado.repo` file has the following line:

```
baseurl=https://repos-avocadoproject.rhcloud.com/static/fedora-$releasever-noarch/
```

I just can't understand how you'd have `1.1.1` as a valid Fedora version.  What kind of system are you using? Did you play with the packaging system?

**Comment by clebergnu** [comment]
Just to make it extra clear, we currently package Avocado for Fedora 22 and 23 only.

**Comment by kanssty** [comment]
Thanks, I have a kind of Fedora like linux environment, and our linux version is 1.1.1, it's a local version number. 
Do you know which $releasever version I can use now? I want to manually fix this number.

**Comment by clebergnu** [comment]
Either 22 or 23. But, if this custom distribution you have is based on
another Fedora version, you may not be able to properly use those
packages.  Then I would suggest you to look into source based installation
instructions.
On May 3, 2016 12:48 AM, "kanssty" <notifications@github.com> wrote:

Thanks, I have a kind of Fedora like linux environment, and our linux
version is 1.1.1, it's a local version number.
Do you know which $releasever version I can use now? I want to manually fix
this number.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/avocado-framework/avocado/issues/1179#issuecomment-216429012>

**Comment by kanssty** [comment]
Thank you. Where can I find some doc or material of source base installation? I will try it firstly. Thanks in advance.

**Comment by clebergnu** [comment]
http://avocado-framework.readthedocs.io/en/latest/GetStartedGuide.html#generic-installation-from-a-git-repository

I'm closing this issue, since the problem has been identified.

**Comment by ldoktor** [comment]
@kanssty btw I used to run the new packages on F20 and they worked properly. Avocado is also supported on RHEL, so any RHEL/CentOS/ScientificLinux-like distributions should work as it's only about dependencies and python, which is similar in all distros (There are few differences in RHEL vs. Fedora as some dependencies use different names and such, but in general it should work).

**Comment by kanssty** [comment]
Thank you.
