### ISSUE TITLE
How to completely uninstall avocado?

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado#1197]
How to completely uninstall source base installed avocado.

**Comment by ldoktor** [comment]
I believe there is no such method from sources as it's not supported by python's distutils. That's why it's recommended to use distribution (rpm, deb) whenever possible.

If you only `developed` it (`make develop` or `make link`), you can use `make clean`, but that might still leave some files produced by different version behind.

One can try removing it manually. You can see the list of files during `make install`, but usually the main locations are `/usr/lib*/python2.7/site-packages/avocado*`, `/etc/avocado`, `/usr/share/avocado` and `/usr/bin/avocado*`. _But not everything must be related to avocado._

Also note that additional plugins could live in other locations too. Again, you can see the files by running `make install`. For example `avocado-vt` adds `/usr/lib*/python2.7/site-packages/avocado_vt` and `/usr/lib*/python2.7/site-packages/virttest` directories (along with the `/etc/avocado`, ...).

**Comment by kanssty** [comment]
Uninstallation done.
