### ISSUE TITLE
Skip tests in bash

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1244]
Hi,

Is there a way that a bash test can be skipped ?
Right now, a bash test can either be PASS(return 0) or FAIL (return non-zero).
Or, is there a way to do this that I am missing ?

**Comment by ldoktor** [comment]
Hello @narasimhan-v,

unfortunately no, there is currently no way to finish SIMPLE test with SKIP. There is a basic support for extended features for SIMPLE tests, it's used in `examples/tests/simplewarning.sh` test, but right now it only support logging features, making it possible for test to finish with `WARN` instead of `PASS`. So if you're interested you can implement it in a similar fashion.

**Comment by clebergnu** [comment]
@narasimhan-v @ldoktor the fact that `simplewarning.sh` is finishing with `PASS` actually shows we have a bug!

If the Avocado shell utility functions can be found (and sourced) than `avocado_warning` should kick in and Avocado should set this test as `WARN`.  If the sell utility functions do not exist, then the script should terminate abrutably: 

```
$ ./examples/tests/simplewarning.sh 
./examples/tests/simplewarning.sh: line 4: avocado_debug: command not found
$ echo $?
127
```

But this is *not* happening.

Now, with regarding to SIMPLE tests and SKIP: the goal of SIMPLE tests is to really be as simple as possible.  So, the zero/non-zero interface was chosen for that specific reason.

What we want to allow in the future, is the creation of custom test types (and its associated loader) very very easily.  So, you could come with your own `NOT_SO_SIMPLE_EXEC` type of test, that actually understands this expanded set of statuses.

**Comment by ldoktor** [comment]
Ok, quite old problem, let me fix it...

**Comment by narasimhan-v** [comment]
@clebergnu @ldoktor I have 2 implementation suggestion here:
1. Having `avocado_skip` command, which can SKIP the test.
2. Implementing SKIP with the test script's return code, which I have mentioned in my earlier comment.

I guess the first implementation sounds better. Your comments please..

**Comment by clebergnu** [comment]
The problem is we have determined that a test cannot skip itself.  When talking about an `avocado.Test` instance, it's easy to distinguish between the test (`test_xxx()` method) and its setup method.  There's no such thing in a SIMPLE test.

Support for `WARN` is a huge exception/compromise that we have added to our test result definition, and then we mapped to SIMPLE tests with this shell helpers.  But adding support for SKIP within a test execution (because it lacks a setup phase) would be great violation.

Nevertheless, I can see the value in having SKIP for SIMPLE tests, I'm just not convinced we have found the right approach.

**Comment by ldoktor** [comment]
Well basically we have just 3 channels (stdout, stderr, exit_code) available in SIMPLE test. I'd suggest using `stdout` for such task and to minimize the possibility of accidental SKIP, I'd use message in this format:
```
"16:49:48 INFO  | SKIP MySimpleTest (job id 8405e684ef5ae920e2e7dbc96e26348fde244a53)"
```

which should be unique enough and hopefully we have all the bits available (not sure about the test name right now).

What do you thinks, @clebergnu? I think it fits the existing tools.

**Comment by clebergnu** [comment]
Given that we are mindstorming, what about, for `test.sh`, another executable named something like `tests.sh.data/skip` that would be run, and if successfull, would skip the test?

**Comment by adereis** [comment]
SIMPLE tests are called "simple" for a reason. In favor of KISS, I would say we should not introduce the complexity of a test skipping itself to simple tests.

**Comment by clebergnu** [comment]
@adereis the only compromise I'd be willing to consider would be to use an external condition, as in the previous example. Would you consider that or just leave that to a `NOT_SO_SIMPLE_TEST` implementation?

**Comment by adereis** [comment]
I like the solution you're proposing (mostly because in there it's not the test that is skipping itself -- I consider an API for a test to skip itself really bad taste), but what we're doing is creating (or expanding) an interface for simple tests to communicate with the test runner. I see value in such an interface, but I have my doubts if we should be extending it in this adhoc manner instead of spending time designing a proper one.

Anyway, given designing a proper one takes time and would be considered low priority right now, maybe it's a good compromise solution. So I'm not against it.

**Comment by ldoktor** [comment]
Well I see SIMPLE tests as tests not ported to avocado. They could be either very simple, but sometimes you might want to just change few bits and benefit other core features. If you remember avocado is suppose to be language independent, so it should be possible to get the advanced features to other tests too.

I'm not really in favor of hardcoded binary/script in `.data` dir, it restrains the usage quite a lot. But I like the idea of using special location, so how about changing the interface and allow `$test-results/simple-api` file, which could be postprocessed on test end and use it as an interface between avocado API and simple tests (language independent). That would minimize the possibility of accidental match, while it should be available from all languages.

I'd like to spend some time on defining this interface, but the features should be IMO added ad-hock. So far we have the `WARN` and there is a suggestion for `SKIP`. I can imagine this to be bi-directional interface, so at the beginning avocado could set for example wrappers and the test inside could check and react on it (I'm not proposing to implement it, I'm just trying to see what would be needed).

Anyway my point is I don't see SIMPLE tests as something SIMPLE. I see them more-like non-ported tests and we ought to provide some level of control over the execution to them at least with respect to test results.

PS: I'm not proposing this to be a solution for universal API, if one wants to write tests in ruby, they should implement RUBY test which should help mapping the python API to RUBY. This should be focused on BASH and simple executions with additional benefits.

**Comment by adereis** [comment]
I guess it should be clear by now, with so many replies and so many brainstorms, that this is not a simple discussion (pun intended). We're talking about defining an API, one that will have to be supported and extended in the future. We don't even have a mechanism for skipping instrummented tests (other than the test skipping itself via setup(), which you all remember was added as a temporary workaround, a compromise solution to a real demand). I know we're all capable of doing it, but this is low priority, we should not be spending time on it right now. 

My suggestion: KISS. There's no way to skip a simple test right now. A workaround is to add a WARNING message to the log and exit(0) at the beginning of the script.

**Comment by clebergnu** [comment]
The bug on warning has been fixed, and SIMPLE tests are intended to be kept as is.  Other test types/loaders can be created with extra fetures.
