### ISSUE TITLE
High avocado cpu consumption

### ISSUE THREAD

**Issue by lmr** [avocado-framework/avocado#1343]
I got this bug report on scylla-cluster-tests: https://github.com/scylladb/scylla-cluster-tests/issues/129:

I'm not sure what we can do to improve on that front, but let's see if we can figure something out.

**Comment by clebergnu** [comment]
@lmr just wondering, based on your report, if you get to verify that this is indeed related to the polling that Avocado does on test processes.  As the polling is basically built around [multiprocessing.Queue.get()](https://docs.python.org/2.6/library/multiprocessing.html#multiprocessing.Queue.get) it shouldn't be CPU intensive.  Also, any additional info you have on that would certainly help to find the core root cause.

**Comment by lmr** [comment]
I don't know if polling is actually the responsible for a perceived high CPU usage, it was just a guess. I'll have to start profiling avocado executions to see if it indeed is the one to blame.

That said, scylla-cluster-tests should consume a lot of CPU due to the fact we keep many SSH connections/sessions to cluster nodes (but the CPU usage should correctly point the SSH processes rather than the avocado python process).

**Comment by ldoktor** [comment]
OK, I looked at the code and the fault probably is on avocado side, not in test handling, but the process library... The `scylla-cluster-tests` runs stress command using `avocado.utils.process` and probably uses timeout. The problem is that when using timeout, the process library polls without any timeout, consuming high cpu, which is definitely not necessary. Let me take care of that...

Simple reproducer is:

```python
from avocado.utils import process
a=process.run("sleep 30", timeout=31)
```

**Comment by clebergnu** [comment]
@lmr PR #1350 has been merged.  Please check if it solves the specific issue you're experiencing.  Thanks!

**Comment by lmr** [comment]
Yes, #1350 solves the high CPU consumption. Thank you so much for looking into this, guys! Please backport the fixes to the 36lts branch.
