### ISSUE TITLE
Porting of netpipe tests from autotest to avocado

### ISSUE THREAD

**Issue by santhosh93** [avocado-framework/avocado#1487]
I am working on porting the netpipe test from autotest : https://github.com/autotest/autotest-client-tests/tree/2780b7c9c39037a39a089176a34ea258dbf10591/netpipe

Here they use barrier class in autotest framework to connect the client and server as below:
Server side Code [from autotest netpipe.py]:
            self.job.barrier(server_tag, 'start', 600).rendezvous(_all)
            self.server_start(args)
            self.job.barrier(server_tag, 'stop', 300).rendezvous(_all)

The Same type of implementation is not found in avocado.
So, I just used normal socket and sys modules to connect client and server like as below :
Server side Code [sample code of mine]:
            server_sock = self.create_bind_socket(self.server_ip)
            server_sock.listen(1)
            connection, client_address = server_sock.accept()
            self.server_start(args)
            connection.close()

And the Test runs fine and Passes in avocado.

Few things I need to Understand:
1 - Can I use the socket methods directly in test and run it?
2 - Or should I Add to avocado framework these socket functionalities??
3 - Or something similar to barrier class in autotest need to be added in avocado ??

Please, let me know how can I proceed with developing the test.

Thanks in advance.

**Comment by PraveenPenguin** [comment]
@apahim @ldoktor can you please have a look in to this issue .

Regards
Praveen

**Comment by ldoktor** [comment]
Hello @santhosh93, I'm sorry it took too long, we discussed it on the meeting and the thing is that currently there is no support for barriers in avocado yet. Once I sent a PR which contained barrier support for avocado, but we decided not to include it and we're still waiting for a counter proposal, but there are more urgent matters right now, so we don't expect any solution in the near future.

So unless you have few months to wait, I'd recommend those solutions sorted by my preference:

1. Use standard python's multiprocessing mechanisms (barrier support was added in python3 :disappointed: but there are some other ways to make it work)
2. Recover the barrier implementation from my avocado's PR, turn it into a util and send it to avocado
3. Implement other barrier mechanism
4. Use autotest's barrier mechanism (which I really dislike, it's ugly, complex, hard to use, ...)

The (1) does not require any changes in avocado, (2) would require a lot of polishing as my PR was a proof of concept focused on multi-machine-parallel-execution, the (3) could be even better and the (4) might not need any changes to avocado, but I'm not sure how the canceling would work. It'd need some exploration.

I'm curious how this turns out. If you decide to cook something up in avocado, I'd recommend sending RFC first (at least basic overview of your approach).

Regards,
Lukáš

**Comment by ldoktor** [comment]
Hello guys, are there any updates on this card? Currently we have the multi-stream RFC in progress, which should also cover some kind of barrier mechanism but apart from that we do not plan to add any extra support. Anyway custom `avocado.utils` sync mechanisms are always welcomed so if you already developed a way to synchronize data feel free to send us an improvement.

I'm closing this issue as I believe it contains all the info needed and we do not plan to prepare such API (unless it corresponds the multi-stream RFC which is likely).
