### ISSUE TITLE
Running in-tree ./scripts/avocado doesn't list sub-commands

### ISSUE THREAD

**Issue by stsquad** [avocado-framework/avocado#1496]
According to the README you should be able to run avocado directly from the source tree. On a fresh checkout on my Ubuntu Xenial 16.04 machine running:

    ./scripts/avocado --help

Yields the help text with an empty subcommands:

    subcommands:
      valid subcommands
    
      {}                    subcommand help

**Comment by clebergnu** [comment]
Just run `make develop` and you should be good to go.

**Comment by stsquad** [comment]
@clebergnu follow up question. Is there a way when running in in tree mode to point to additional plugins? In my case I'm looking at virtualisation testing but it seems the avocado.conf isn't read when running directly out of tree.

**Comment by ldoktor** [comment]
@stsquad when running from within the main git directory avocado uses the `$git/etc/...` configs (while still using the user's `~/.config/avocado/avocado.conf`). I'm not sure what do you mean by additional plugins, but you can inspire from `avocado-vt` and `avocado-virt`. They are separate plugins, but if you store them in the same parent directory as avocado:

```
$ cd $avocado_path
$ cd ..
$ ls
aexpect  avocado-framework.github.io  avocado-presentations  avocado-virt        avocado-vt
avocado  avocado-misc-tests           avocado-server         avocado-virt-tests
```
you can link them together in order to work from sources:

```
$ cd avocado
$ make link
...
>> SKIP ../avocado-misc-tests
>> LINK ../avocado-virt
>> SKIP ../avocado-presentations
>> LINK ../aexpect
>> SKIP ../avocado-framework.github.io
>> LINK ../avocado-server
>> LINK ../avocado-vt
>> LINK ../avocado-virt-tests
...
$ avocado plugins
...
vt      Avocado VT/virt-test support to 'run' command
vt-list Avocado-VT/virt-test support for 'list' command
...
```
