### ISSUE TITLE
[RFC] Create the namespace avocado.utils.linux

### ISSUE THREAD

**Issue by lmr** [avocado-framework/avocado#1686]
I was wondering whether we could create the namespace `avocado.utils.linux`, so `avocado.utils.linux_modules` would become `avocado.utils.linux.modules`, or maybe even `avocado.utils.linux.drivers`, to borrow a more widely known naming convention from the Windows world. We could even move `software_manager` and other modules to that namespace.

**Comment by apahim** [comment]
+1

**Comment by ldoktor** [comment]
Well splitting modules can sometime bring easier navigation, but at the same time this change would be intrusive (all existing tests would have to be modified). Also it might be even worse if in the future we come up with the same API for windows (not likely) or other posix systems, which might start to be messy. I'm not sure whether this change is worth it and whether we do expect so many os-specific utils (in `avocado.utils`). There are other possible categories which might require category (like architecture, debug, ...) so before changing well established names I'd prefer to go through existing modules and try to find the most suitable categories. Right now I think we don't have so many utils so I'd wait. Maybe categorizing according to OS is the best, maybe it isn't. We'll see that in the future.

Additionally if we are to make changes, I'd suggest `kernel_modules` as the name, because in linux word there are many things which could be called modules.

**Comment by lmr** [comment]
We can easily make changes backwards compatible by putting a few imports that would re-create the old namespaces (ideally with a deprecation message).

About waiting, sure, I'm not suggesting that we rush into doing this.

About naming, that's why I thought `drivers` could have been a reasonable name. `kernel_modules` could be good as well.

**Comment by ldoktor** [comment]
Yep, I do like `drivers` and it could be even generic and has win/unix backends... But that would require someone who would utilize it 😄.

**Comment by clebergnu** [comment]
@lmr the idea has been, AFAICT, well accepted.  I'm closing this issue (as it was a RFC) and waiting for further updates (PRs?) on this.  Thanks!
