### ISSUE TITLE
seach for tests also in imported files/modules

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1792]
Hi,
I have two files like:
a.py:
```
from avocado import Test
class a(Test):
    def test(self):
        print "a"
```
b.py
```
from avocado import Test
import a

class b(Test):
    def test(self):
        print "b"
```

I would like to call `avocado run ./b.py` and it shlould also detect that in imported class a is class with instrumented test.

**Comment by lmr** [comment]
Can you elaborate about the use case? It seems like this is not a very standard way of organizing tests and supporting libraries, and right now it doesn't seem a very compelling workflow to try to support.

**Comment by ldoktor** [comment]
@lmr don't worry, I'm already questioning Jan and we'll update this when we find the right description...

**Comment by jscotka** [comment]
Hi Lucas, my usecase is, to have some test in `/usr/lib/python*/site-packages/xxx` module and don't care about path, just have import in file and it also seach for test classes in imported modules

**Comment by ldoktor** [comment]
OK so basically the aim of this issue is to also introspect all the imported modules and search for avocado tests in them. This is something I'd be personally against. Another solution would be to `from a import a`, which would in a dynamic world make the `a:a.test` part of the new module, but still I don't much like that because it means introspecting every imported object whether it is (per chance) an avocado test.

The solution is basically to adjust your command-line to run `avocado run a.py b.py` which does basically what you want to do.

Anyway we discussed the motivation, which was to have the test in PYTHONPATH not knowing exactly where and still execute it along with your normal test. I don't think that is a proper way and I suggested splitting the tests from the library code and put the library in PYTHONPATH and the test into `/usr/share` location, making the path predictable (and actually properly separating the scopes).

Let me close this issue and feel free to reopen if my proposed solution does not work for you.

**Comment by jscotka** [comment]
could you please revise that. I need this so much.

**Comment by ldoktor** [comment]
Basically this is about allowing to create test-suites. The options are:

1. Create directories and use symlinks to create the test suites `avocado run suite1/ suite2/`
2. Create `\n` separated files and use `avocado run $(cat suite1)`
3. Implement `csv`/`tsv`/`\n` loader which would basically work as (2) without the need to use subshell `avocado run --loader suite suite1`
4. Add support to introspect imported classes and in `suite1.py` use `from foo import Test1; from bar import Test3` and run it by `avocado run suite1.py`

This is ordered by my preferences. I don't think we should support introspecting modules (as mentioned in the original report), but with all eyes closed I can imagine iterating through imported objects as well as defined classes in the same manner, but I see this as a last option, so @jscotka would any of (1-3) work for you, or do you insist on (4)?

**Comment by jscotka** [comment]
Yes I prefer solution (4). 
__User storie:__ I've created `modulelint.py` at the beginning and more modules uses that. And I've now reconsidered, that it hasto be divided to more files like: `rpmvalidator, check_compose`, and other.

And I would like to keep backward compatibility for those whose use just `modulelint,py`. It is harder to force more people to change theirs Makefiles to use another way how to get `module-lint` tests

And yes, it happens because I've done bad decision at thee beginning and I've done modulelint as single python file. But in case avocado provides __(4)__ it solves this situation in the most elegant way for keeping backward compatibility for similar cases.

**Comment by clebergnu** [comment]
@jscokta the new `:avocado: recursive` tag at least partially address this.

Wrt solution 4, I understand that you'd like to have a file such as:

```python
from passtest import PassTest
from sleeptest import SleepTest
```

And then when run `avocado list -V includetests.py ` get the following result:

```
Type         Test                                           Tag(s)
INSTRUMENTED includetests.py:Sleep.test                     
INSTRUMENTED includetests.py:Pass.test                      fast
```

That is currently not possible because we look for a `class` statement in the file that was given as a test reference (`includetests.py` in this case).  This currently requires:

```python
from passtest import PassTest
from sleeptest import SleepTest

class Pass(PassTest):
    """
    :avocado: recursive
    """
    pass


class Sleep(SleepTest):
    """
    :avocado: recursive
    """
    pass
```

Let us know if the `:avocado: recursive` tag and any other of the listed solutions would work for you.

**Comment by ldoktor** [comment]
@jscotka does the current `:recursive:` tag works for you, or is there something else you need regarding this support?

**Comment by jscotka** [comment]
Hi, yes, this works for me.
     Honza

**Comment by ldoktor** [comment]
Great, closing this issue.
