### ISSUE TITLE
Ideal usage of --job-timeout argument

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#2019]
The `--job-timeout` argument of `avocado run` seems to be not working for greater values than 86400 which is provided in `DEFAULT_TIMEOUT` in `avocado/core/runner.py`. 

A sample sleep test with --job-timeout of 90000 seconds gets interrupted at 86400 seconds. But gets interrupted with a lesser --job-timeout than 86400.
```
# avocado run avocado-misc-tests/generic/sleep.py --job-timeout 90000
(1/1) tests/avocado-misc-tests/generic/sleep.py:sleep.test: INTERRUPTED (86400.00 s)
```
Is this timeout expected to work only for lesser values than 86400 ( or whatever is provided as `DEFAULT_TIMEOUT`)?

**Comment by ldoktor** [comment]
The `DEFAULT_TIMEOUT` is a convenience value to avoid complete hangs, but the timeout can be overridden by test params (by setting `timeout` variable in test `self.timeout = 90000` or by using varianter to set the `timeout` eg `--mux-inject /run:timeout:90000`). Note it has to be non-zero, otherwise default is applied.

I don't think we should automatically match the test timeout to job timeout as you might have multiple tests and you might want to get results of the later ones. No timeout is also something we did not wanted to allow, because one should know how long tests is suppose to take.

Anyway does the proposed solution work for you?

**Comment by narasimhan-v** [comment]
@ldoktor I would say there is no need of `DEFAULT_TIMEOUT` at all, because some tests can take longer to complete based on its input. It is difficult to determine / guess them. We should just use the `timeout` that the user gives via the different means you have mentioned.

**Comment by ldoktor** [comment]
@narasimhan-v can you please send an RFC to `avocado-devel`? It's been a while since we decided this, but I still believe adding default timeout is a good idea, but as we added `job-timeout` maybe more people would be inclined to remove this.

As for the different values, that's why it's configurable from `self.params`, one can always override it based on the variant they are running.

**Comment by narasimhan-v** [comment]
@ldoktor Sure, will do.

**Comment by harish-24** [comment]
@ldoktor @narasimhan-v Thanks for clarifying on this. Closing this.
