### ISSUE TITLE
RFE: Avocado Lint

### ISSUE THREAD

**Issue by mhradilek** [avocado-framework/avocado#2136]
As a beginner using avocado I have trouble with avocado not recognizing test as instrumented. I suggest that "avocado list -V particulartest.py" runs some basic tests for common mistakes like missing docstring directives.

Took me a while stripping test to bare bones until i found my mistake.

**Comment by apahim** [comment]
Could I ask what was wrong in your test? If your mistake was forgetting the `avocado: enable` docstring, we need it to recognize the test as a test when it's not directly inheriting from `avocado.Test`. From your suggestion, we should identify the docstring-less test as a test to then tell the user that the docstring is missing? In that case, docstring would not be needed at all, since test would have been already identified. Apart from the docstrings chicken/egg problem, I don't see any other syntax check that cannot be covered by pylint itself. 

(By the way, we have recently introduced a docstring called `recursive`. When used, it will discover tests not only in the test class, but in all its parents until the base of the chain. We plan to make the recursive behavior the default behavior, so no docstrings will be needed anymore.  Not sure when this change will take place though.)

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RFE: Run pylint when test is python file but does not look like INSTRUMENTED test](https://trello.com/c/HB3ha5Xe/1090-rfe-run-pylint-when-test-is-python-file-but-does-not-look-like-instrumented-test)

**Comment by ldoktor** [comment]
@apahim the issue really is when you modify the test and forget `:` or so (therefor SyntaxError) suddenly the test is invisible to `avocado run`  and Avocado suggests `avocado list -V` which does not help as it only says `Does not look like an INSTRUMENTED test, nor is it executable` but it used to look like one 1 minute ago. Usually pylint is around so using it (on `.py` files on verbose listing) might help.

**Comment by mhradilek** [comment]
@apahim The point is that if you are calling the command on a particular file you are likely expecting it to be test or contain it. In automatic discovery it would make no sense. And yes it was missing the directive.

**Comment by ldoktor** [comment]
We have 2 cards: https://trello.com/c/bT5qP6y5/1354-loader-in-fileloader-lets-allow-individual-discoveries-to-report-their-issues-and-report-that-instead-of-generic-not-instrumente and https://trello.com/c/HB3ha5Xe/1090-rfe-run-pylint-when-test-is-python-file-but-does-not-look-like-instrumented-test that should improve the situation, let me close this issue and keep track of the progress on trello (feel free to vote there to increase the priority, or even take over the card and send PR)
