### ISSUE TITLE
RFC: Profillers to be per test configurable

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#2248]
How about making profilers as per test configurable rather than framework wide.

Usecase:
Not all tests needs all profilers to be configured, for example, cpu tests might not memory/io profilers
but we might have to  run all tests together as suite.

How about driving/enabling it through test yaml?

Do not have an implementation proposal right now, but lets have it brainstormed about possibility and shortcoming/ other good ideas here.

**Comment by narasimhan-v** [comment]
@sathnaga That is very good to have.

I am not sure what is the best possible approach to implement it. My view is, since there is a `tagging` available for test, we can use that to identify the profilers needed when running that test. But it would not be user configurable.

**Comment by ldoktor** [comment]
Well the question is how useful would such option be, because it'd add complexity to test execution while the gain would be just a few spared bytes in the output. I can imagine being able to specify filters to not start some of the profilers for some tests.

Anyway it'd be nice to send RFC with some use-cases and ideally examples on the usage to the mailing list so we can actually brainstorm and not just record the wish without details.

**Comment by sathnaga** [comment]
@ldoktor Sure, get your point, will re-validate the usecase and will bring it to mailing list with more details if required. Closing it for now.
