### ISSUE TITLE
running network test like netperf and iperf

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#2331]
How is this implemented? can anyone guide me to some example. Also, how we are runing HW test like bonnie and lmbench tests with avocado.

**Comment by PraveenPenguin** [comment]
@omps you can refer https://github.com/avocado-framework-tests/avocado-misc-tests for tests.

after cloning repo it can be run as 

`avocado run avocado-misc-tests/perf/lmbench.py`

**Comment by PraveenPenguin** [comment]
netperf , lmbench  and bonnie test is already part of this repo

**Comment by ldoktor** [comment]
Exactly, Avocado is a testing framework that can ran (just about) anything as a test. There are some "example/tests" included, but they are definitely not intended for testing. Out there there are several repositories with tests and the most advocated one is the https://github.com/avocado-framework-tests/avocado-misc-tests because sharing tests is better for all parties.

Let me close this issue as I believe it was addressed by @PraveenPenguin but feel free to re-open it to get more hints if needed.
