### ISSUE TITLE
Avocado variants documentation incorrect?

### ISSUE THREAD

**Issue by twirrim** [avocado-framework/avocado#2345]
Example documentation page: http://avocado-framework.readthedocs.io/en/56.0/optional_plugins/varianter_yaml_to_mux.html#yaml-to-mux-plugin

The pattern is repeated elsewhere in reference to the command, but the argument `-m` doesn't seem to be valid, one example from that page: `avocado variants --tree -m <file>`.

From a quick grep through all the files in avocado it doesn't seem like "-m" is a valid argument anywhere?

**Comment by apahim** [comment]
It is part of the varianter `yaml_to_mux` plugin: https://github.com/avocado-framework/avocado/blob/master/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py#L352

**Comment by twirrim** [comment]
hmm.  It's also mentioned here: http://avocado-framework.readthedocs.io/en/56.0/WritingTests.html#accessing-test-parameters, no reference to the yaml_to_mux plugin there.

**Comment by apahim** [comment]
Yep, that part of documentation deserves an update. Are you going to send a PR for that? Otherwise, I will create a card in our short-term backlog. Just let me know. Thanks!

**Comment by ldoktor** [comment]
Well it's mentioned there because to date we don't have other way to provide params than yaml_to_mux plugin (or pict plugin) but we do have planned support for stock way to provide params and then it might be possible to improve the documentation to avoid such dependencies.

On the other hand having references to yaml_to_mux/pict plugins from params documentation seems useful to me. At least users would learn about the possibilities.

**Comment by ldoktor** [comment]
The documentation had been split and links to mux plugin were included. There is still one step to avoid using it in examples, but it is not really related to this issue.
