### ISSUE TITLE
[RFE] better 'human readable' logs provided by avocado

### ISSUE THREAD

**Issue by phracek** [avocado-framework/avocado#2447]
Hi folks, I would like to ask you if it's possible to provide some short explanation logs into avocado out.
Nowadays output looks like this:
```
(02/13) /usr/lib/python2.7/site-packages/moduleframework/tests/static/dockerfile_lint.py:DockerInstructionsTests.test_from_directive_is_valid:  FAIL (0.04 s)
```

What about to improve it to something like that:
```
(2/13) "Test whether from directive is valid": FAIL (0.04 s)
```

This can improve better understanding of tests what's going on.

I am able to prepare a PR, but please point me which python codes are relevant.

**Comment by clebergnu** [comment]
Hi @phracek this sounds interesting indeed.  A few initial thoughts:

1) Avocado uses the Test ID (what you see by default) in a number of places, including in the results in the filesystem, and it's a good idea to keep them consistent;
2) Adding a "Test Short Description" concept, which can be optional (think of SIMPLE tests), seems to be the way to go here.  For this, looking at `avocado/core/safeloader.py` to parse a Python file and get the description from the docstring is a good idea.
3) With that information, I'd tweak the human UI to show that description, maybe in addition to the Test ID.  This can, of course, also be made configurable.

Let me know if this makes sense to you.

**Comment by phracek** [comment]
Hi @clebergnu , of course Test ID should remain as we see them by default.
I like second option. This could be a way. If Test Short Description is present, then show it in the output instead of Test ID. Personally, I don't want to mix Test ID with "Test Short Description" like you mentioned in third option.

**Comment by phracek** [comment]
@clebergnu Do you have an idea when `avocado` will support it? 
Or let me know how to do it or debug it and I will send you a PR.

**Comment by clebergnu** [comment]
@phracek `safeloader` os probably one of the modules you want to start with.  Please attempt to hack something and propose a draft and I'll provide as much guidance as I can get.

**Comment by ldoktor** [comment]
@phracek do you want to keep this issue open (meaning do you actively work on this) or is it something long-term that eventually you'd welcome, but you don't need it? Btw not sure whether this is relevant, but for comparison reasons I wanted something like: https://trello.com/c/vDNFZF5h/1340-add-support-to-format-jobdata-results-into-various-formats which might overlap with your idea a bit (you want to see something else than test-id while executing it, I want to see different columns while reporting results).

Anyway let us please know about your intentions, otherwise we'll close this as we don't plan on working on this any time soon.

**Comment by phracek** [comment]
You can close the issue. Your trello card seems to be similar or even better then this issue. Support for various formats seems to solve my problem.
