### ISSUE TITLE
does the Avocado Test Framework have an interface to test the rest API？

### ISSUE THREAD

**Issue by lnsyyj** [avocado-framework/avocado#2649]
Hello, 
does the Avocado Test Framework have an interface to test the rest API? Is there a test example document?

**Comment by ldoktor** [comment]
I'm not aware of any utils that would be present in Avocado to help with rest API testing, but there are plenty of python projects that can be leveraged to do that.

Another approach would be to use some external tool via `--external-runner` and use Avocado only as the man in the middle (gather sysinfo, record case for replay and store everything in well defined format).

**Comment by lnsyyj** [comment]
@ldoktor Thank you very much, I think if avocado has such a feature, it will be very convenient to use.

**Comment by ldoktor** [comment]
Yep, unfortunately I don't see anyone from the core team working on it in any foreseeable future so let me close this issue. Anyway if you decide to add such support, please send a RFC to avocado-devel mailing list (or just a PR here, but sending RFC first can avoid many troubles while attempting to get things upstream).

**Comment by lnsyyj** [comment]
Okay thank you

**Comment by ldoktor** [comment]
I mean we are open to all ideas, that's why we have robot and glib plugins, but we can't do everything ourselves. These plugins for example came from the community, we refined them and put in our sources. So if you plan to use Avocado for this kind of testing, do try to develop even just a dirty proof-of-concept, we might be able to help you polishing it...
