### ISSUE TITLE
Utility for network

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#2684]
Hi,

What is the take on an ethernet interfaces related utility ?
netifaces was previously used in the tests, but later removed from avocado dependencies.

**Comment by ldoktor** [comment]
Hello @narasimhan-v, the basic Avocado dependencies are set in `setup.py` (and `optional_plugin/*/setup.py`) and are limited to Avocado itself. Then we have the `requirements.txt` which contains slightly bigger set and includes some optional dependencies of `avocado.utils`. But the `netifaces` (I assume that's the one you complain about) is not used in Avocado project, therefore it should not be included and people should install it along with other test dependencies if necessary.

Note that for example Avocado-vt uses `netifaces` and it mentions it in their `requirements.txt` (and PR to include it in `setup.py` is under review)

As for the why, it had been done when we cleaned the dependencies to avoid installing so many of them when not needed to minimize the footprint. Many tests do not require those (not even all utils deps) so they were removed.

**Comment by narasimhan-v** [comment]
@ldoktor I agree about the utilities not using them, but most of the network related tests in https://github.com/avocado-framework-tests/avocado-misc-tests/tree/master/io/net use `netifaces`.

So, how are we to proceed here ?
1. Add netifaces to requirements.txt in avocado and proceed using it in tests ?
2. Implement a utility in avocado with the necessary network related modules, and use that in the tests ?

**Comment by ldoktor** [comment]
Simplest is to modify your provisioning scripts to add your requirements. I mean you need to install "gcc" and other non-python dependencies somewhere, right? And that is also the right place for python dependencies (and ideally from distribution packages and not from pip)

Later if you decide other people would benefit from having those, you could create `requirements.txt` within `avocado-misc-tests` and share those between other people. They'll learn to install requirements from the test provider as well.

The (2) is also an option as once it becomes Avocado dependency, it'll be listed in `requirements.txt` (also not in `setup.py`, because it's not a core dependency).

**Comment by narasimhan-v** [comment]
@ldoktor The idea was to try and bring back the requirement which was existing previously, but  I understand the idea behind (2) :-)

I will have it in my provisioning script. Thanks

**Comment by ldoktor** [comment]
OK, thank you for understanding. I think it makes sense to at least put these into `avocado-misc-tests/requirements.txt`, but it should not exists in `avocado` as other users might want to run different tests and they don't need such requirements.
