### ISSUE TITLE
pip install error about version

### ISSUE THREAD

**Issue by Blackrose** [avocado-framework/avocado#2685]
Hi, I use pip to install avocado. But some packages have unresolved dependency version about django.The avocado need django 1.6, django-rq 1.1.0.While the django-rq 1.1.0 needs django 1.8.So, It's seems the avocado use old django version.

**Comment by ldoktor** [comment]
Avocado itself does not depend on `django`, only the `avocado-server` requires it. I'm just guessing but haven't you tried installing `pip install avocado; pip install avocado-server`? Because in `pip` the Avocado project is called `avocado-framework`, because `avocado` was previously existing `django` project.

If that's not the case, please mention the steps that leads to this issue.

**Comment by clebergnu** [comment]
@Blackrose I think you're referring to the Django extension: http://avocado.harvest.io/.  This is a different project.
