### ISSUE TITLE
default execution order

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#2742]
Hi,

Is there any reason `DEFAULT_EXECUTION_ORDER` is set to `variants-per-test`.
https://github.com/avocado-framework/avocado/blob/master/avocado/core/runner.py#L278

**Comment by ldoktor** [comment]
Hello @narasimhan-v, the reason is historical and there was no reason in changing it as for different use-cases different mode is better. For example I use the default for iotests, because that way I see how the same test behaves under different setting.

As for the example from open-power-host-os, it worries me. Tests should never depend on other tests so calling one test `test_setup`, other `test_run` and third `test_cleanup` raises red flag to me. Anyway I understand the need to share some setup, but that should happen during `setUp` phase and the recommended way is to use `teststmpdir` to signal certain setting, for example:

```
init = os.path.join(self.teststmpdir, "my_identifier")
if os.path.exists(init):
    with open(init) as variant:
        if self.get_variant() == variant.read():
            return

# do the setup
```

Still this will perform better if you have multiple `test*` methods with the same setup so I'm open on suggestions regarding this change. Would you please summarize things and send this on `avocado-devel` to get wider audience?

**Comment by narasimhan-v** [comment]
> As for the example from open-power-host-os, it worries me. Tests should never depend on other tests so calling one test test_setup, other test_run and third test_cleanup raises red flag to me. Anyway I understand the need to share some setup, but that should happen during setUp phase and the recommended way is to use teststmpdir to signal certain setting

@ldoktor The need for this arises from https://github.com/avocado-framework-tests/avocado-misc-tests/pull/964
I need the test to either go through the full cycle / just create / just remove bonding. We previously used to handle it via yaml parameters: like `setup: True`, `cleanup: False` will create and exit. In bonding, I took the approach of `test_setup` and `test_cleanup`.

Can you explain a bit more on why such a method is not preferred ?

**Comment by ldoktor** [comment]
Each test is a standalone entity. Sometimes they require setup so "setUp" and "tearDown" methods were developed to allow, well, set up and tear down. Failures during setup/teardown are visibly different from failures during test method, so there should be no need for that. In case of shared setup, one still has to check before each test, whether the setup was performed or not, because one can execute only a subset of tests, not the whole class/file of tests.

Second because the order of executed tests is not granted (well it is actually configurable in Avocado, IIRC, by default it's how they appear in the file, but I might be mistaken). Now imagine you update python and suddenly instead of `test_setup test test_cleanup` it discovers the tests in different order and executes `test test_cleanup test_setup`. Will it affect your testing?

Yes, the shared setup might be a bit more pain, but maybe we can add a helper method to simplify this. Something like `self.setup_performed(True/False)`(True =>  consider `self.params` as well). It should not be hard to develop and maybe it'd help. What do you think?

```python
def setUp(self):
    if self.setup_performed(True):  # Use self.teststmpdir to check whether setup was performed
        return
    self.performing_setup()  # Write to self.testtmpdir that setup was performed and set func-at-exit to perform clean-up
    ...
```

The only change we'd have to do is to re-order the func-at-exit, because to get the original setting they'd have to be executed in reversed order (because usually we remember previous state and in case previous state was already set by another setUp we need to revert them in reversed order to get to the original value).

@clebergnu what is your call on this? Should I write a trello card about it?

**Comment by clebergnu** [comment]
Each test being a standalone entity, as @ldoktor put it, is part of a conscious design decision.  It may look like it gets in the way of some tests, but it's actually there to also help the overall design of tests.  How can you tell that a failure in test "b" was not really caused by test "a"?  TBH, I actually consider the default (process based) isolation of Avocado too weak, and would not be afraid to see a stronger isolation by default.

Anyway, on functional tests, that require system setup, such as the one @narasimhan-v points out, it may be too costly to do the setup over and over again.  A few solutions which are not built into the framework at this point:

1) Rely on an automation tool that can quickly verify and apply the setup steps before every test.  Ansible is such a tool that could be called on every `setUp()`, and would only change things if necessary.
2) Use a job-wide flag: `TESTSTMPDIR` is a compromise that could be used to flag the `setup_performed()` condition.  A simple `perform_setup(); touch($TESTSTMPDIR/setup_performed)` could be used

@narasimhan-v did we understand your pain points? Do these ideas make sense?

**Comment by narasimhan-v** [comment]
Thanks @ldoktor @clebergnu .

I understand the point of tests being standalone.

The one place where I currently do not see this being applicable too well is the below scenario.
I need to run tests on the bond interfaces like:
Bonding.test_setup
NetDataTest.testbigping
ScpTest.test_ping
ScpTesttest_floodping
TcpdumpTest.test
Bonding.test_cleanup

What is the best approach here ?

**Comment by ldoktor** [comment]
Well the question is whether you need to run multiple set of tests in one job. If yes that developing `test_cleanup` is probably the only way you have until we have Job API, because we do have the means to create shared setup, but we don't have means to initiate test_cleanup at ones will (only after all tests were executed. Usually it should not matter, but in case some tests require the default configuration, there is no way. But you should perhaps extract those tests and always call full setup and cleanup with the full name (avoid `avocado run bonding` and instead run `avocado run bonding.test_setup bonding_tests bonding.test_cleanup`, which should make sure the order is correct.

If you only need to run the single setup, ẗhan the best option is, how @clebergnu pointed out, a tool that is designed to perform machine provisioning as those tools usually double-check the correct setting (eg. ansible).

Easier to start with/use but without the guarantee something had been set is to use `TESTSTMPDIR` to share info about the performed setup. Simplest form is `touch $TESTTMPDIR/$TEST_NAME` which would not be optimal for your case, but there are other variants. You could create a main setup file based on subset of tests (for example `$TESTSTMPDIR/avocado-misct-tests`).

Further you can replace the `touch` with serialization of the performed setup, for example `pickle.dumps(self.params)` (not sure whether it's pickable) or have a `self.dump_params` method that would only compare variables related to setup (to avoid setup execution on unrelated variable change).

You can as well use multiple files to store different parts of setup. For example you can do something like (simplified):

```
if not self.disks_setup():  # uses self.params and `TESTSTMPDIR/disks` to store the current setup
    self.setup_disks()
if not self.nics_setup():  # uses self.params and `TESTSTMPDIR/nics` to store the current setup
    self.setup_nics()
...
```

Or you can always setup and teardown, which might be slower at first but you know your environment is set.

And as usual, you can combine all of these... Anyway your example makes sense to me, but you have a hidden knowledge one needs to understand when looking at tests and results.

**Comment by clebergnu** [comment]
@narasimhan-v have you managed to implement your use case?

**Comment by clebergnu** [comment]
@narasimhan-v if you have any updates on your use case, please reopen this issue.

**Comment by narasimhan-v** [comment]
I forgot to comment here:
Setting a default execution order does not solve my case.
If I want to run multiple tests at once, and if each of them use different order, there is no way now to specify that.

**Comment by ldoktor** [comment]
Well you can always use yaml_loader to fine-tune your job. It is very flexible.

**Comment by ldoktor** [comment]
I mean: https://avocado-framework.readthedocs.io/en/latest/optional_plugins/yaml_loader.html
