### ISSUE TITLE
aexpect-helper processes are left uncleaned

### ISSUE THREAD

**Issue by rayx** [avocado-framework/avocado#2997]
I notice that the test system on which I ran avocado-vt test have a lot of aexpect-helper processes left uncleaned. 

<pre>
# ps -ef | grep aexpect-helper | wc -l
38
</pre>

Among them some were used to run tcpdump:

<pre>
  |-aexpect-helper,1097 /usr/bin/aexpect-helper
  |   `-bash,1099 -c tcpdump -tnpvvvi any 'port 68 or port 546' && echo idZoV4XX > /dev/null
  |       `-tcpdump,1101 -tnpvvvi any port 68 or port 546
</pre>

and some were to run nc:

<pre>
  |-aexpect-helper,1582 /usr/bin/aexpect-helper
  |   `-bash,1583 -c nc -U /var/tmp/avocado_agPUm8/serial-serial0-20190103-224135-slBlOQ3A && echo 
cROnYdK1 > /dev/null
  |       `-nc,1584 -U /var/tmp/avocado_agPUm8/serial-serial0-20190103-224135-slBlOQ3A
</pre>

I ran avocado-vt in a normal way. Usually I wait until all tests run to finish, and sometimes I press Ctl-C to interrupt it and then wait it to abort. I often run it in screen, though I don't think that matters.

I don't know how often this happens (e.g, whether every time I run avocado, there are new aexpect-helper processes left uncleaned, or it just happens sometime).

**Comment by clebergnu** [comment]
@rayx As you can imagine, it's pretty hard to track down what set of conditions ended up leaving those processes running on your system.

Having said that, it's a tough call (and tough task) for a test runner like Avocado to keep track of all processes that are started by test code (either directly or indirectly though secondary frameworks like Avocado-VT).

Avocado fires the test process itself, and when it has to interrupt a test (process), it tries its best to clean up all the processes it knows about (for instance look at https://github.com/avocado-framework/avocado/blob/5f450f6f8e1fbb59b0a7a1d4f9201b07c037d17c/avocado/utils/process.py#L806).  That doesn't mean that it will do the same thing on every other situation, including when tests are terminating and reporting success.

So, TBH, I'm not sure how to deal with this issue instead of maybe looking at leaks on the Avocado-VT side.

**Comment by willianrampazzo** [comment]
Hi @rayx, this issue was opened more than a year ago. Is this issue still valid? Have you checked on the Avocado-VT side?

**Comment by rayx** [comment]
@willianrampazzo I don’t use avocado any more so I have no new information about the issue. Feel free to close it if you find you can’t reproduce it. That said, I suspect if it helps to run avocado in a dedicated cgroup to prevent (or investigate) “process leaks” issue like this. (It has been a while since I worked on Linux, so this is just a vague suggestion).

**Comment by willianrampazzo** [comment]
I'm closing this as we are planning to move to a new runner soon. If anyone reaches this problem, feel free to reopen this issue.
