### ISSUE TITLE
nrunner is freezing when using venvs

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3559]
If you call the following command from a venv:

```
(venv) $ avocado nrun selftests/unit/test_astring.py
```

and you have some `avocado-*` runners in your `~/.local/bin/`, then nrunner will try to execute them instead of the venv ones. This will cause to nrun to freeze in "Finished spawning tasks":

```
Results server started at: 127.0.0.1:8888
2-selftests.unit.test_astring.AstringTest.test_tabular_with_console_codes spawned
5-selftests.unit.test_astring.AstringTest.test_safe_path spawned
1-selftests.unit.test_astring.AstringTest.test_tabular_output spawned
9-selftests.unit.test_astring.AstringTest.test_to_text_decode_is_text spawned
6-selftests.unit.test_astring.AstringTest.test_is_bytes spawned
3-selftests.unit.test_astring.AstringTest.test_tabular_output_different_no_cols spawned
7-selftests.unit.test_astring.AstringTest.test_is_text spawned
4-selftests.unit.test_astring.AstringTest.test_unicode_tabular spawned
10-selftests.unit.test_astring.AstringTest.test_to_text spawned
8-selftests.unit.test_astring.AstringTest.test_to_text_is_text spawned
Finished spawning tasks
```

This was fixed with:

```
$ rm -rf ~/.local/bin/avocado*
```

But we need to proper handler this, or at least document this.

**Comment by clebergnu** [comment]
This basically happens because the `avocado-runner-*` do not find the Python libraries and crash, right? I think the proper solution here can include:

* The spawner listing the task status after its spawned
  - already partially in place with the "is alive" message
* The formal definition of the signaling of success or failure of spawning, so that a crash can not only be "detected" because the task is not "alive" anymore, but also because some type of status/returncode was explicitly given
* A verbose option that describes the status/returncode mentioned in the previous point

With that, if the user has any kind of `avocado-runner-$KIND` that is misbehaving, the behavior would be the same.

**Comment by clebergnu** [comment]
This is ancient, still about the `nrun` command.  I'm betting and assuming this is no longer applies.
