### ISSUE TITLE
nrunner is always returning 0 on command-line

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3663]
When running `avocado-runner-* runnable-run` from a command-line, we always get 0 as return code:

```
(python3) # avocado-runner-tap runnable-run -k tap -u perl -a /tmp/non-existing-file
{'status': 'running', 'timestamp': 1584637750.9655268}
{'status': 'error', 'returncode': 2, 'timestamp': 1584637750.9661703}
(python3) #echo $?
0
```

**Comment by clebergnu** [comment]
While a nrunner "runner application" should be returning more meaningful status codes, this specific example you give is actually the intended behavior.

If you think about it, the `avocado-runner-tap` ran successfully, and it doesn't really matter that the "runnable" (think of it as a payload) had a specific result.  The status server (within the `nrun` command) doesn't care about the status code of the "runner application" to tally the overall results. 

The way to go here, IMO, is to let the "job" layer know how a given runner application finished (let's say to tell the user the result is unknown because it crashed), but not to let that influence the test results.

**Comment by beraldoleal** [comment]
> If you think about it, the `avocado-runner-tap` ran successfully, and it doesn't really matter that the "runnable" (think of it as a payload) had a specific result. The status server (within the `nrun` command) doesn't care about the status code of the "runner application" to tally the overall results.

I see and understand. Ok, I agree that we should not care about the returncode of the "payload execution", but maybe we could handle a few cases because to me when "a file does not exist" should not be a "successfully ran", the same for permission denied.

**Comment by beraldoleal** [comment]
@clebergnu, I'm still thinking about this. Trying to think like the user that is adopting Avocado:

Before Avocado:
```
$ perl mytests/foo.t 
```

This is a basic execution of a test that will return a non 0 value if something goes wrong.

Then, when using an Avocado runner, it will return 0 even if something goes wrong (permission denied or file not found). This will "force" the user to check for the output of the specific runner.

Sorry, but it looks like I'm missing something. What it is?
