### ISSUE TITLE
Add support to collect tests output results on the Next Runner

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3695]
The current runner knows that test outputs results are located at `test-results` folder.

With the PR #3685 bein approved the Next Runner will have support to Spawners (currently only Process and Podman). We need to implement methods inside those spawner classes to collect the test-results for each case and give back those results to the user.

**Comment by beraldoleal** [comment]
@clebergnu do you would like to add any requirements details here?

**Comment by clebergnu** [comment]
Right now the runner implementations (`ExecTestRunner`, `PythonUnittestRunner`, etc) will produce some types of output that will be yielded, *usually* being sent to an nrunner status server (`avocado.core.nrunner.StatusServer`).  But that's only a very limited amount of data, and some tests will want to produce additional types of output, specially in the form of directories/files.

The current Avocado test class (`avocado.core.test.Test`), which happens to be the base of not only the `INSTRUMENTED` tests, but also every other supported test type, makes this available to tests:

https://avocado-framework.readthedocs.io/en/77.0/api/test/avocado.html#avocado.Test.logdir

And it also makes an `outputdir` available, so that tests can store other type of relevant artifacts:

https://avocado-framework.readthedocs.io/en/77.0/api/test/avocado.html#avocado.Test.outputdir

We need to come up with a way to:
 * (maybe) Allow tests to describe whether they need a directory to put logs and/or other artifacts (generic output files)
 * Tell the tests where this (or these) directories are
 * Decide on a way for whoever manages the tests/tasks (let's say the job layer, spawner, etc) to collect those files so that they'll be kept as part of those test results.

My initial reaction is that `Runnables` could be configurable with a set of core features, such as:
 * Needs a temporary dir: True/False
 * Needs an output dir: True/False

Those would be managed by the runner, and those would be exposed to actual payload. For instance, if we're talking about a `ExecTestRunner`, it could make that information available to the executable by setting `AVOCADO_RUNNER_WORKDIR=/var/tmp/testXXXX/workdir` and `AVOCADO_RUNNER_OUTPUTDIR=/var/lib/avocado/testXXXX/outputdir`. If other highly customized runners are written, they could expose this is a more native way to the tests they're supposed to run.

These are old and very rough experiments on the ideas above:

https://github.com/clebergnu/avocado/commit/8e9ff6daa188dcf41fcd8ba685a09e1251e3bf0e
https://github.com/clebergnu/avocado/commit/335b9fd9886fa44b8678f18f0a6019ff6197e4d7

**Comment by clebergnu** [comment]
This is also part of #3700

**Comment by beraldoleal** [comment]
In order to follow a "keep it simple approach" and as discussed on a meeting with @clebergnu today, we have decided a few things that I would like to share here for broader visibility:
  
>  (maybe) Allow tests to describe whether they need a directory to put logs and/or other artifacts (generic output files)

For now, we decided that the Next Runner will have a similar approach to the current runner: We are ***not*** allowing tests to describe whether they need or not a specific directory (for temporary and/or persistent outputs).

The temporary directory is the `AVOCADO_RUNNER_WORKDIR` and the output directory is the `AVOCADO_RUNNER_OUTPUTDIR`, both are going to be created anyway, without the need to the boolean features/settings.

> Tell the tests where this (or these) directories are

For now, we are going to use a uniform mechanism: Environment Variables.

> Decide on a way for whoever manages the tests/tasks (let's say the job layer, spawner, etc) to collect those files so that they'll be kept as part of those test results.

This is the main work of this issue, and I'm working on it.

**Comment by beraldoleal** [comment]
This is done in theory.

`avocado jobs get-output-files` is implemented but we have two problems:

1. When using the Job API, Spawner architecture is not triggered. This is required by `get-output-files`;
2. When using the `avocado nrun` command, the Job() is not triggered. This is required to populate the `job-results/` dir and required by this.

We have two issues (#3866 and #3700) to handle this.

**Comment by beraldoleal** [comment]
Hi @clebergnu I think that this was working before cb9de3914a69c08fd7e976d72deeb727db461352. Looks like `_populate_task_logdir()` call was dropped.
