### ISSUE TITLE
NRunner plugin: support failfast feature

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3870]
The failfast feature does not currently work with the nrunner plugin.  A job such as:

```python
#!/usr/bin/env python3

import sys
from avocado.core.job import Job

config = {'run.references': ['/bin/true', '/bin/false', '/bin/true', '/bin/true'],
          'run.test_runner': 'nrunner',
          'run.failfast': 'on'}

with Job(config) as j:
    sys.exit(j.run())
```

Should produce:

```
JOB ID     : dfa077af08bee71d82f4741b2ca5682ac94eef38
JOB LOG    : /home/cleber/avocado/job-results/job-2020-06-02T01.03-dfa077a/job.log
 (1/4) /bin/true: PASS (0.01 s)
 (2/4) /bin/false: FAIL: (0.06 s)
Interrupting job (failfast).
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by beraldoleal** [comment]
@clebergnu With the new architecture things are more distributed now and tasks can be running on a container or remote host.

Thinking about a `PodmanSpawner` or a `RemoteSpawner`, I can imagine both stopping the virtual machine or the container to avoid remaining tasks to be running after the "Interrupted" is received. Or we could have remote "agents/watchdogs". There are many ways to go here.

@clebergnu How do you imagine this possible implantation?

**Comment by willianrampazzo** [comment]
I think the main piece here is the scheduler. It will have a high-level view of each test execution and should know its status.

We should make the testers aware that running tests in parallel with the `failfast` parameter will not have the same "performance" when compared with today's implementation.

The implementation I can think of here is into the scheduler. As soon as one test fails, it is the scheduler's responsibility to signal to the running tests to cancel its execution in the best effort. Some tests may take some time to return its confirmation of cancelation because they were into high I/O, or any other reason, meaning the `failfast` will not be as fast as the current implementation, but a best effort to finish the job execution.

**Comment by beraldoleal** [comment]
Part of #4802
