### ISSUE TITLE
Future settings module doesn't read/respect global configuration file 

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3884]
As found out during a fix for the sysinfo per-test issue/PR (https://github.com/avocado-framework/avocado/pull/3875#issuecomment-638276984) we're not seeing configurations being respected when they're added to the system wide configuration.

When they're added to the user specific configuration file, `~/.config/avocado/avocado.conf`, then they are.

**Comment by beraldoleal** [comment]
@clebergnu Unless I missed something, it is working for me:

(Please keep in mind that since I'm using virtualenv, my dirs starts at venv root)

```bash
$ cat /home/local/src/venvs/avocado-latest/etc/avocado/avocado.conf
[sysinfo.collect]
enabled = off
```
^ This is my "global/system" file.

```bash
$ avocado run /bin/true
....
ls -la ~/avocado/job-results/latest/sysinfo/
ls: cannot access '/home/local/avocado/job-results/latest/sysinfo/': No such file or directory
```

What could happen is if something is declared on the "local" config file, this will override the "global" on, because we are respecting the following order: Code Default Values, Global Config, Local Config, Command Line Args.

**Comment by clebergnu** [comment]
The issue here is actually the lack of support for the "Pythonic system wide" configuration file:

```
/usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/etc/avocado/avocado.conf
```

The `avocado.core.settings` module has to support it, while `avocado.core.future.settings` lacks it.
