### ISSUE TITLE
Job: add support for multiple test suites

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3958]
In an Avocado job, there's a common use case for treating different groups of tests in different ways., but there's no way to do that right now.  For example, one group of tests may benefit from using a variants configuration, while a second group is not parameterized, and thus, would not benefit from being run repeatedly with different parameters in variants.

One approach would be to create different jobs, but this brings a large number of challenges of its own, such as the generation and presentation of results.  The other approach, which is described here, which does not conflict with a future development of supporting multiple jobs, is to support multiple test suites within a single job.

Some objective points and use cases:
 * Do not require the YAML2Mux Loader for scenarios with multiple set of tests and multiple parameters
 * Allow *any* of the new Job API features and configurations items (as much as it makes sense) to be applied to one specific test suite, but not to another
 * We don't have to care, at this time, with parallelization of test suites, it may be a future development (while a given Job Runner implementation, say `runner_nrunner.py` may run tests in a suite in a parallel way).

There's some prior work on it here:
 * https://github.com/clebergnu/avocado/commits/wip/next/job_api_multiple_suites

Specially on those commits:
 * https://github.com/clebergnu/avocado/commit/88e480b8df57ce08fb74b730c70901a4c592a0dc
 * https://github.com/clebergnu/avocado/commit/27403712fc39f8a6c6157c6204448ec227e4fb1d

But this is mostly a PoC.  One special area to focus on is the interface we'll give Job writers, that is, how people writing jobs will be able to supply their custom test suites and (optionally) different configuration to different suites.

**Comment by clebergnu** [comment]
@ldoktor as the author of YAML2Mux loader, your input is very much appreciated here.

@wainersm you've requested such a feature some time ago, so you be willing to track or provide extra requirements and points here.

**Comment by beraldoleal** [comment]
Part of this work was started here #3974

**Comment by ldoktor** [comment]
Hello @clebergnu, not sure what you want to hear from me, but basically to some extent it's possible to do that via yaml2mux loader so it should be possible directly within a job as well, provided you find a way to let the job know how to tweak the environment for different tests/groups of tests.

As for the parallel execution there used to be variables stored globally, for example the gdb execution, but IIRC that was removed, or wasn't it? Then there are the settings that are also stored globaly which might be a problem.

You might want to re-evaluate my suggestion to execute each test in a different process via exec instead of fork, that should allow all kinds of combinations, without that someone will always create something in a global namespace that might collide (even if just a  plugin like avocado-vt which uses global namespace heavily). Anyway, as mentioned earlier, the parallel execution is not a priority at this point.

**Comment by pevogam** [comment]
Hi @clebergnu, I wonder if this doesn't complicate things too much. The main goal it could achieve from what I see so far is to make it possible for a user to pack all sorts of diverse tests with their own config scopes into one job and group them into test suites of some reusable configuration, thus creating complex additional hierarchy within the code base which could be achieved with a bit exra care on the side of the user.

Do we have some measurements or feedback on how many users run such diversity of tests in a single job? I have mostly seen diverse types of tests included in some examples of avocado usage in the documentation but in practice I see users run a single type of tests comprising their test suites (and thus variant definitions). How frequent is this use case?

You mention that it is hard to collect and present results when even in cases of different types of tests the user would split them in separate jobs. Can you provide more details? All the result formats avocado provides are separate plugins independent of the test types in use. Perhaps we would need a way to combine these in a single report of the same format but other than that what are more specific challenges? Isn't such a result collection from a very diverse tests within the same job also a problem using the same starting point?

**Comment by beraldoleal** [comment]
@pevogam I saw a few comments about this on a different thread, I hope @clebergnu has solved your questions. Not sure if is there any.

But since this was already implemented and merged, I would like to close this.

**Comment by pevogam** [comment]
@beraldoleal: Sure, go ahead and thanks for asking first! I guess this was the better place to write to instead of there but we are more or less already done with some conclusions in the other thread. I am curious if you too have some opinion or conclusion from what we discussed to share there. Any thoughts would be good.

**Comment by beraldoleal** [comment]
@pevogam Ok, I will comment there, was a little busy with some other issues. Thanks for the quick reply.

**Comment by beraldoleal** [comment]
@clebergnu I'm closing this because afaik this is merged already. Please feel free to reopen if this wasn't the case.
