### ISSUE TITLE
[BUG - Job API] 'core.show' is not respected in some scenarios

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3997]
Considering the following example:

```
#!/usr/bin/env python3

import sys

from avocado import Test
from avocado.core.job import Job


class PassTest(Test):
    def test(self):
        config = {'core.show': ['none'],
                  'run.references': ['/bin/true']}
        with Job(config) as j:
            j.run()


if __name__ == '__main__':
    config = {'run.references': [__file__],
              'core.show': ['app']}
    with Job(config) as j:
        sys.exit(j.run())
```

When running it as ` python3 /tmp/passjob_with_test.py`, the value of `core.show` inside the test is not respected and the `core.show` value in the `main` block is used.

The same happens if we run `avocado run /tmp/passjob_with_test.py`. The value of `core.show` inside the test is not respected. The value of `core.show` from the main block is also ignored, but I think this is expected in this case.

**Comment by beraldoleal** [comment]
@willianrampazzo this seems to me be very similar to #4001. Is that the case? It is ignored because we have an explicity `if __name__ == '__main__':` right?

**Comment by willianrampazzo** [comment]
I don't think so, the outside Job (in the `main` block) should not influence the config of the inside Jobs (in the `test` block).

**Comment by beraldoleal** [comment]
The outside job is not executed if you are calling from avocado, right?

**Comment by willianrampazzo** [comment]
> The outside job is not executed if you are calling from avocado, right?

Right! And that is working fine.

**Comment by beraldoleal** [comment]
@willianrampazzo I got you, makes sense. Since @richtja is already assigned, I will leave this issue with him.

**Comment by richtja** [comment]
@beraldoleal I already did some tests here and it looks on a problem with configuration of the logging system.

**Comment by richtja** [comment]
@beraldoleal @willianrampazzo, Hi I find out what problem is here, but I can not see an easy solution so I appreciated help here. 

The problem is with a reconfiguration of logging handlers when the new configuration is set. In [here](https://github.com/avocado-framework/avocado/blob/master/avocado/core/job.py#L142) you can see that logging handlers are reconfigured when the new job starts but only if wasn't configured before. So when the Job in `__main__` already configured the loggers, the `PassTest` Job can't reconfigure it anymore. And actually the problem is deeper because when avocado starts it uses configuration from [cmd or default ones](https://github.com/avocado-framework/avocado/blob/master/avocado/core/app.py#L74) because of that the value of `core.show` from the main block is also ignored.

The problem is how this reconfiguration should look like. Because we need to disable the logging configuration of the main Job when the test Job starts and then enable it when the test Job ends. This configuration is not an easy task because we have to take care about all user [options.](https://avocado-framework.readthedocs.io/en/80.0/guides/writer/chapters/logging.html) 
Actually I am still learning how the avocado logging system works, so maybe there is something which I don't see.
