### ISSUE TITLE
Validate / document Test API changes from 69.x to 82.0

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4231]
The goal here is to produce something like:

https://avocado-framework.readthedocs.io/en/81.0/releases/lts/69_0.html#porting-tests-test-api-compatibility

One approach would be to check out the `examples/tests` folder from the 69lts branch, and attempt to run them with the latest and greatest Avocado.

**Comment by beraldoleal** [comment]
Hi @clebergnu , afaict, I have found a few issues:

1. we removed the implicity module import `main` from `avocado` and now is part of `avocado.core` only;

  I guess that this is a good thing, otherwise will have the main import even when we don't need it;

2. Some TypeErrors when using the `utils/gdb`, here is one example:

```
2020-09-10 14:58:33,638 test             L0915 ERROR| TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```
3. An error with synctest:

```
ERROR 1-synctest.py:SyncTest.test -> CmdError: Command '/var/tmp/avocado_v7asymoj/avocado_job_43r8tj83/1-synctest.py_SyncTest.test/synctest/synctest 100 10' failed.
```

Besides that, we are good.

**Comment by clebergnu** [comment]
So I guess only item 1 would impact test writers, and deserve attention.  The migration instructions would be to drop the main import unless really needed, and if needed, resort to the Job API instead. See `examples/jobs/passjob_with_test.py`.

**Comment by beraldoleal** [comment]
@clebergnu, I'm closing this then. Please, feel free to reopen.
