### ISSUE TITLE
Support for progressing output in the `process.run` function

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#4244]
I have a developer colleague that told me he cannot use the function:

https://github.com/avocado-framework/avocado/blob/704dc9ee59f382eb157221b012d05cb255d4b7c7/avocado/utils/process.py#L972

despite it being the standard function for commands on the hosts in avocado. The reason he reported was that the command he runs in code is "qemu-img convert", which will output the progress of the conversion in percentage. Since he wants to display the progress in the logs, he is using aexpect's `run_fg` instead that accepts an `output_func` which is called when new content is available. Do I miss something or the process module doesn't seem to support it?

**Comment by willianrampazzo** [comment]
Hi @pevogam, I did a quick test here, and it seems to be working without problems.

Here is the test example I used:

```
from avocado import Test
from avocado.utils import process


class Run(Test):

    def test(self):
        cmd_result = process.run('qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw')
        self.assertEqual(cmd_result.exit_status, 0)
```

And here is an excerpt from the `job.log` file:

```
2020-09-18 14:58:40,688 process          L0604 INFO | Running 'qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw'
2020-09-18 14:58:40,693 process          L0416 DEBUG| [stdout]     (0.00/100%)
2020-09-18 14:58:41,559 process          L0416 DEBUG| [stdout]     (1.01/100%)
2020-09-18 14:58:41,612 process          L0416 DEBUG| [stdout]     (2.02/100%)
2020-09-18 14:58:41,673 process          L0416 DEBUG| [stdout]     (3.04/100%)
2020-09-18 14:58:41,738 process          L0416 DEBUG| [stdout]     (4.05/100%)
2020-09-18 14:58:41,802 process          L0416 DEBUG| [stdout]     (5.06/100%)
2020-09-18 14:58:41,846 process          L0416 DEBUG| [stdout]     (6.06/100%)
2020-09-18 14:58:41,896 process          L0416 DEBUG| [stdout]     (7.07/100%)
2020-09-18 14:58:41,948 process          L0416 DEBUG| [stdout]     (8.07/100%)
2020-09-18 14:58:42,007 process          L0416 DEBUG| [stdout]     (9.07/100%)
2020-09-18 14:58:42,066 process          L0416 DEBUG| [stdout]     (10.08/100%)
2020-09-18 14:58:42,121 process          L0416 DEBUG| [stdout]     (11.11/100%)
2020-09-18 14:58:42,176 process          L0416 DEBUG| [stdout]     (12.11/100%)
2020-09-18 14:58:42,232 process          L0416 DEBUG| [stdout]     (13.13/100%)
2020-09-18 14:58:42,284 process          L0416 DEBUG| [stdout]     (14.13/100%)
2020-09-18 14:58:42,338 process          L0416 DEBUG| [stdout]     (15.14/100%)
2020-09-18 14:58:42,394 process          L0416 DEBUG| [stdout]     (16.16/100%)
2020-09-18 14:58:42,447 process          L0416 DEBUG| [stdout]     (17.18/100%)
```

The percentages will show up as `DEBUG` messages.

I can also tell the logger to add it as `INFO`:

```
from avocado import Test
from avocado.utils import process


class Run(Test):

    def test(self):
        cmd_result = process.run('qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw')
        self.log.info(cmd_result)
        self.assertEqual(cmd_result.exit_status, 0)
```

Then, I see at the end of `job.log` the following:

```
2020-09-18 14:59:52,357 run              L0012 INFO | command: 'qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw'
exit_status: 0
duration: 6.9040846824646
interrupted: False
pid: 115392
encoding: 'UTF-8'
stdout: b'    (0.00/100%)\r    (1.01/100%)\r    (2.02/100%)\r    (3.04/100%)\r    (4.05/100%)\r    (5.06/100%)\r    (6.06/100%)\r    (7.07/100%)\r    (8.07/100%)\r    (9.07/100%)\r    (10.08/100%)\r    (11.11/100%)\r    (12.11/100%)\r    (13.13/100%)\r    (14.13/100%)\r    (15.14/100%)\r    (16.16/100%)\r    (17.18/100%)\r    (18.18/100%)\r    (19.19/100%)\r    (20.20/100%)\r    (21.20/100%)\r    (22.21/100%)\r    (23.21/100%)\r    (24.23/100%)\r    (25.23/100%)\r    (26.25/100%)\r    (27.26/100%)\r    (28.27/100%)\r    (29.28/100%)\r    (30.29/100%)\r    (31.31/100%)\r    (32.32/100%)\r    (33.33/100%)\r    (34.34/100%)\r    (35.36/100%)\r    (36.36/100%)\r    (37.37/100%)\r    (38.38/100%)\r    (39.39/100%)\r    (40.40/100%)\r    (41.40/100%)\r    (42.41/100%)\r    (43.42/100%)\r    (44.42/100%)\r    (45.43/100%)\r    (46.44/100%)\r    (47.45/100%)\r    (48.45/100%)\r    (49.46/100%)\r    (50.47/100%)\r    (51.48/100%)\r    (52.48/100%)\r    (53.49/100%)\r    (54.50/100%)\r    (55.51/100%)\r    (56.53/100%)\r    (57.54/100%)\r    (58.56/100%)\r    (59.58/100%)\r    (60.59/100%)\r    (61.60/100%)\r    (62.62/100%)\r    (63.62/100%)\r    (64.63/100%)\r    (65.65/100%)\r    (66.66/100%)\r    (67.68/100%)\r    (68.69/100%)\r    (69.70/100%)\r    (70.70/100%)\r    (71.72/100%)\r    (72.73/100%)\r    (73.75/100%)\r    (74.75/100%)\r    (75.77/100%)\r    (76.78/100%)\r    (77.78/100%)\r    (78.79/100%)\r    (79.81/100%)\r    (80.81/100%)\r    (81.84/100%)\r    (82.85/100%)\r    (83.86/100%)\r    (84.87/100%)\r    (85.88/100%)\r    (86.89/100%)\r    (87.90/100%)\r    (88.91/100%)\r    (89.92/100%)\r    (90.92/100%)\r    (91.93/100%)\r    (92.94/100%)\r    (93.95/100%)\r    (94.96/100%)\r    (95.97/100%)\r    (96.98/100%)\r    (98.00/100%)\r    (99.01/100%)\r    (100.00/100%)\r    (100.00/100%)\r\n'
stderr: b''
```

Do you have more details about the test your colleague is running so we can try to reproduce here?

**Comment by pevogam** [comment]
> Hi @pevogam, I did a quick test here, and it seems to be working without problems.
> 
> Here is the test example I used:
> 
> ```
> from avocado import Test
> from avocado.utils import process
> 
> 
> class Run(Test):
> 
>     def test(self):
>         cmd_result = process.run('qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw')
>         self.assertEqual(cmd_result.exit_status, 0)
> ```
> 
> And here is an excerpt from the `job.log` file:
> 
> ```
> 2020-09-18 14:58:40,688 process          L0604 INFO | Running 'qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw'
> 2020-09-18 14:58:40,693 process          L0416 DEBUG| [stdout]     (0.00/100%)
> 2020-09-18 14:58:41,559 process          L0416 DEBUG| [stdout]     (1.01/100%)
> 2020-09-18 14:58:41,612 process          L0416 DEBUG| [stdout]     (2.02/100%)
> 2020-09-18 14:58:41,673 process          L0416 DEBUG| [stdout]     (3.04/100%)
> 2020-09-18 14:58:41,738 process          L0416 DEBUG| [stdout]     (4.05/100%)
> 2020-09-18 14:58:41,802 process          L0416 DEBUG| [stdout]     (5.06/100%)
> 2020-09-18 14:58:41,846 process          L0416 DEBUG| [stdout]     (6.06/100%)
> 2020-09-18 14:58:41,896 process          L0416 DEBUG| [stdout]     (7.07/100%)
> 2020-09-18 14:58:41,948 process          L0416 DEBUG| [stdout]     (8.07/100%)
> 2020-09-18 14:58:42,007 process          L0416 DEBUG| [stdout]     (9.07/100%)
> 2020-09-18 14:58:42,066 process          L0416 DEBUG| [stdout]     (10.08/100%)
> 2020-09-18 14:58:42,121 process          L0416 DEBUG| [stdout]     (11.11/100%)
> 2020-09-18 14:58:42,176 process          L0416 DEBUG| [stdout]     (12.11/100%)
> 2020-09-18 14:58:42,232 process          L0416 DEBUG| [stdout]     (13.13/100%)
> 2020-09-18 14:58:42,284 process          L0416 DEBUG| [stdout]     (14.13/100%)
> 2020-09-18 14:58:42,338 process          L0416 DEBUG| [stdout]     (15.14/100%)
> 2020-09-18 14:58:42,394 process          L0416 DEBUG| [stdout]     (16.16/100%)
> 2020-09-18 14:58:42,447 process          L0416 DEBUG| [stdout]     (17.18/100%)
> ```
> 
> The percentages will show up as `DEBUG` messages.
> 
> I can also tell the logger to add it as `INFO`:
> 
> ```
> from avocado import Test
> from avocado.utils import process
> 
> 
> class Run(Test):
> 
>     def test(self):
>         cmd_result = process.run('qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw')
>         self.log.info(cmd_result)
>         self.assertEqual(cmd_result.exit_status, 0)
> ```
> 
> Then, I see at the end of `job.log` the following:
> 
> ```
> 2020-09-18 14:59:52,357 run              L0012 INFO | command: 'qemu-img convert -p -f qcow2 -O raw /home/wrampazz/temp/ubuntu.qcow2 /home/wrampazz/temp/ubuntu.raw'
> exit_status: 0
> duration: 6.9040846824646
> interrupted: False
> pid: 115392
> encoding: 'UTF-8'
> stdout: b'    (0.00/100%)\r    (1.01/100%)\r    (2.02/100%)\r    (3.04/100%)\r    (4.05/100%)\r    (5.06/100%)\r    (6.06/100%)\r    (7.07/100%)\r    (8.07/100%)\r    (9.07/100%)\r    (10.08/100%)\r    (11.11/100%)\r    (12.11/100%)\r    (13.13/100%)\r    (14.13/100%)\r    (15.14/100%)\r    (16.16/100%)\r    (17.18/100%)\r    (18.18/100%)\r    (19.19/100%)\r    (20.20/100%)\r    (21.20/100%)\r    (22.21/100%)\r    (23.21/100%)\r    (24.23/100%)\r    (25.23/100%)\r    (26.25/100%)\r    (27.26/100%)\r    (28.27/100%)\r    (29.28/100%)\r    (30.29/100%)\r    (31.31/100%)\r    (32.32/100%)\r    (33.33/100%)\r    (34.34/100%)\r    (35.36/100%)\r    (36.36/100%)\r    (37.37/100%)\r    (38.38/100%)\r    (39.39/100%)\r    (40.40/100%)\r    (41.40/100%)\r    (42.41/100%)\r    (43.42/100%)\r    (44.42/100%)\r    (45.43/100%)\r    (46.44/100%)\r    (47.45/100%)\r    (48.45/100%)\r    (49.46/100%)\r    (50.47/100%)\r    (51.48/100%)\r    (52.48/100%)\r    (53.49/100%)\r    (54.50/100%)\r    (55.51/100%)\r    (56.53/100%)\r    (57.54/100%)\r    (58.56/100%)\r    (59.58/100%)\r    (60.59/100%)\r    (61.60/100%)\r    (62.62/100%)\r    (63.62/100%)\r    (64.63/100%)\r    (65.65/100%)\r    (66.66/100%)\r    (67.68/100%)\r    (68.69/100%)\r    (69.70/100%)\r    (70.70/100%)\r    (71.72/100%)\r    (72.73/100%)\r    (73.75/100%)\r    (74.75/100%)\r    (75.77/100%)\r    (76.78/100%)\r    (77.78/100%)\r    (78.79/100%)\r    (79.81/100%)\r    (80.81/100%)\r    (81.84/100%)\r    (82.85/100%)\r    (83.86/100%)\r    (84.87/100%)\r    (85.88/100%)\r    (86.89/100%)\r    (87.90/100%)\r    (88.91/100%)\r    (89.92/100%)\r    (90.92/100%)\r    (91.93/100%)\r    (92.94/100%)\r    (93.95/100%)\r    (94.96/100%)\r    (95.97/100%)\r    (96.98/100%)\r    (98.00/100%)\r    (99.01/100%)\r    (100.00/100%)\r    (100.00/100%)\r\n'
> stderr: b''
> ```
> 
> Do you have more details about the test your colleague is running so we can try to reproduce here?

Thanks a low @willianrampazzo! I will compare this with our cases.

**Comment by samiraguiar** [comment]
@willianrampazzo thanks for the quick reply. I'll try to detail the problem I was facing as initially described by my colleague @pevogam. After digging a bit I believe I've managed to understand the issue better and I can hopefully provide more context.

Although `process.run` does send the output of the process to the logs, in my tests when the underlying process buffers the output (e.g. libc when it detects [a pipe instead of a terminal](https://www.pixelbeat.org/programming/stdio_buffering/)), this happens at once when the process finishes or when the buffer is full, while what I needed was "live output" (i.e. unbuffered).

Here's an example:

**File sample.py**
This is a simple script to simulate a program that takes a while to finish, with 3 seconds between each call to `print()`.
```python
import time

for i in range(5):
    print(f'[logme] Iteration #{i}')
    time.sleep(3)
```

**File avocado-test.py**
Now this is the avocado test script with four test cases; each test invokes the `python` binary, which is an example of a program that buffers the output on pipes.

```python
import logging
from avocado import Test
from avocado.utils import process
from aexpect.client import run_fg

class Run(Test):
    def test_buffered(self):
        logging.debug('[logme] Test #1 | process with buffer (no live logging)')
        exit_status = process.run('python sample.py').exit_status
        self.assertEqual(exit_status, 0)

    def test_unbuffered_python(self):
        logging.debug('[logme] Test #2 | process without buffer via python -u (live logging ok)')
        exit_status = process.run('python -u sample.py').exit_status
        self.assertEqual(exit_status, 0)

    def test_unbuffered_script(self):
        logging.debug('[logme] Test #3 | process without buffer via script (live logging ok)')
        exit_status = process.run('script -q -c "python sample.py" /dev/null').exit_status
        self.assertEqual(exit_status, 0)

    def test_unbuffered_aexpect(self):
        def output_func(output):
            logging.debug(output)

        logging.debug('[logme] Test #4 | process without buffer via aexpect (live logging ok)')
        exit_status, _ = run_fg('python3 sample.py', output_func=output_func, timeout=60)
        self.assertEqual(exit_status, 0)
```

Test case #&#x2060;1 is a normal run that will be buffered, meaning the output will be sent to the logs at once. Test case #&#x2060;2 solves the problem by disabling buffering with the `-u` switch (which is not available in `qemu-img`). Test case #&#x2060;3 is a possible workaround where the buffer is disabled by running the command through [Unix's `script`](https://www.unix.com/man-page/Linux/1/script/). Test case #&#x2060;4 replaces `process.run()` with `run_fg`, which I think works because `aexpect` [uses a pseudo-terminal](https://github.com/avocado-framework/aexpect/blob/be9be4b325ac1da7b0c908e82f1d2c52e43dfd2f/scripts/aexpect_helper#L75).

I've run the test with:
`python -m avocado run avocado-test.py`

And the excerpt from `job.log` (only relevant lines shown):
```
2020-09-22 01:59:01,259 test             L0008 DEBUG| [logme] Test #1 | process with buffer (no live logging)
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #0
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #1
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #2
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #3
2020-09-22 01:59:16,290 process          L0416 DEBUG| [stdout] [logme] Iteration #4
.......
2020-09-22 01:59:16,325 test             L0013 DEBUG| [logme] Test #2 | process without buffer via python -u (live logging ok)
2020-09-22 01:59:16,341 process          L0416 DEBUG| [stdout] [logme] Iteration #0
2020-09-22 01:59:19,344 process          L0416 DEBUG| [stdout] [logme] Iteration #1
2020-09-22 01:59:22,347 process          L0416 DEBUG| [stdout] [logme] Iteration #2
2020-09-22 01:59:25,350 process          L0416 DEBUG| [stdout] [logme] Iteration #3
2020-09-22 01:59:28,350 process          L0416 DEBUG| [stdout] [logme] Iteration #4
.......
2020-09-22 01:59:31,386 test             L0018 DEBUG| [logme] Test #3 | process without buffer via script (live logging ok)
2020-09-22 01:59:31,404 process          L0416 DEBUG| [stdout] [logme] Iteration #0
2020-09-22 01:59:34,407 process          L0416 DEBUG| [stdout] [logme] Iteration #1
2020-09-22 01:59:37,410 process          L0416 DEBUG| [stdout] [logme] Iteration #2
2020-09-22 01:59:40,413 process          L0416 DEBUG| [stdout] [logme] Iteration #3
2020-09-22 01:59:43,415 process          L0416 DEBUG| [stdout] [logme] Iteration #4
.......
2020-09-22 01:59:46,454 test             L0026 DEBUG| [logme] Test #4 | process without buffer via aexpect (live logging ok)
2020-09-22 01:59:46,516 test             L0024 DEBUG| [logme] Iteration #0
2020-09-22 01:59:49,519 test             L0024 DEBUG| [logme] Iteration #1
2020-09-22 01:59:52,522 test             L0024 DEBUG| [logme] Iteration #2
2020-09-22 01:59:55,523 test             L0024 DEBUG| [logme] Iteration #3
2020-09-22 01:59:58,526 test             L0024 DEBUG| [logme] Iteration #4
```

You can see that in all but the first we have a 3-second pause between each "Iteration..." line, which I believe is caused by the buffer.

In the logs you posted there does seem to be a pause between the log messages, but I'm not sure if they are indeed unbuffered as the intervals are rather short.
Is this expected behavior? Would you mind checking if I'm missing something here?

The example code from above is also available on [this repository](https://github.com/samiraguiar/avocado-buffer) if you prefer.

**Comment by clebergnu** [comment]
Hi @samiraguiar @pevogam,

You have a point in the sense that process connected to terminals will operate with line based buffering.  But, it's the buffering employed on stdout/stderr that are king, and not really the fact that they are or not terminals.  A non-tty can still operate in unbuffered mode, like your examples 2 and 3.

Unfortunately, AFAICT, Python doesn't make it easy to change the buffering mode of a file.  libc itself provides `setbuf` (and others) though, and it's pretty simple to use:

```c
#include <unistd.h>
#include <stdio.h>

int
main(void)
{
  setbuf(stdout, NULL);
  setbuf(stderr, NULL);

  for (int i = 0; i <= 5; i++) {
    printf("Iteration %u\n", i);
    sleep(3);
  }
  return 0;
}
```

Using `avocado.utils.process.run` with a binary generated from this code will perform similarly to 2, 3 and 4 (live logging OK).

Now, on the output of your example 1, you have this:

```
2020-09-22 01:59:01,259 test             L0008 DEBUG| [logme] Test #1 | process with buffer (no live logging)
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #0
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #1
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #2
2020-09-22 01:59:16,289 process          L0416 DEBUG| [stdout] [logme] Iteration #3
2020-09-22 01:59:16,290 process          L0416 DEBUG| [stdout] [logme] Iteration #4
```

And you may have noticed that the timestamp on the last line (iteration 4) is different.  This is because the even though all the output will be made available to be read at once,  `avocado.utils.process.FDDrainer`, will try to read lines, and log each one of those lines individually.  So between the first line and the last, there was a ~ 1/100th of a second elapsed.  

I don't think the examples that @willianrampazzo posted are similar to these, and I'm  confident that `qemu-img` does not have a buffered stdout.

**Comment by samiraguiar** [comment]
Hi @clebergnu, thanks for taking a look!
I understood your explanation, but I'm not sure I got the conclusion right: do you mean that, although the behavior of `aexpect.client.run_fg` is different than that of `avocado.utils.process.run` (the former doesn't require buffering to be manually disabled), this is by design as buffering happens on file level?

**Comment by samiraguiar** [comment]
Hi everyone, I have retested and reanalyzed the examples provided and indeed, `process.run` and `qemu-img` work correctly together, with output being printed in a progressive manner. The culprit for the issues I have experienced lies elsewhere, so I ask @pevogam to close this issue. Thank you all for the advice and sorry for the confusion.

**Comment by pevogam** [comment]
Thanks @willianrampazzo and @clebergnu for taking the time to elaborate here!
