### ISSUE TITLE
Missing some log information when running tests

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4366]
```bash
$ avocado run --test-runner=nrunner --ignore-missing-references -- selftests/unit/test_utils_partition.py:TestPartition.test_basic
```

This test when skipping should show why is skipping. job.log is not showing that information.

**Comment by clebergnu** [comment]
As of https://github.com/avocado-framework/avocado/pull/4517 most test information is being kept in the *test* results directories.  I wonder if this is a good time, and idea, to avoid duplicating everything into the `job.log`.  If we choose to do that, this issue would be mostly or completely fixed by now.

**Comment by richtja** [comment]
+1 for deleting duplicates from `job.log`

**Comment by clebergnu** [comment]
We are strongly considering not duplicating the raw test's results into the `job.log`, but we want to provide test result information in the `job.log`.  So, if a test "1-foo" passes, that should be easy to spot in the `job.log` file.  Something like:

```
2021-04-11 16:06:59,627 job              L0251 INFO | 1-foo: PASS
2021-04-11 16:08:59,627 job              L0251 INFO | 2-bar: FAIL
```
