### ISSUE TITLE
Nrunners comunication with status server

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4418]
We have to define communication between nrunners and status server and set minimal properties which each message should have. Right now the communication looks like this:

```
{'status': 'started', 'time': 282906.422831419}
{'status': 'running', 'time': 282906.43333344}
{'status': 'finished', 'time': 282906.433379842, 'returncode': 0, 'stdout': b'', 'stderr': b'', 'result': 'pass', 'logdir': '/tmp/result/test-results/1-FailTest.test', 'logfile': '/tmp/result/test-results/1-FailTest.test/debug.log', 'running': False, 'paused': False, 'whiteboard': '}
```
The status server can not check the message and deal with invalid communication. Also, most of the data are sent by the last message which can cause problems when a such message is huge. The communication should look something like this:

```
{'status': 'started', 'time': 282906.422831419, 'returncode': None, 'stdout': b'', 'stderr': b'', 'result': None, 'logdir': '/tmp/result/test-results/1-FailTest.test', 'logfile': '/tmp/result/test-results/1-FailTest.test/debug.log', 'running': True, 'paused': False, 'whiteboard': ''}
{'status': 'running', 'time': 282906.43333344, 'returncode': None, 'stdout': b'', 'stderr': b'', 'result': None, 'logdir': '/tmp/result/test-results/1-FailTest.test', 'logfile': '/tmp/result/test-results/1-FailTest.test/debug.log', 'running': True, 'paused': False, 'whiteboard': ''}
{'status': 'finished', 'time': 282906.433379842, 'returncode': 0, 'stdout': b'', 'stderr': b'', 'result': 'pass', 'logdir': '/tmp/result/test-results/1-FailTest.test', 'logfile': '/tmp/result/test-results/1-FailTest.test/debug.log', 'running': False, 'paused': False, 'whiteboard': ''}
```

**Comment by beraldoleal** [comment]
I agree with you @richtja. We need to revisit that. But I'm not sure if the first message ("started") should have all the keys.

I understand that is "not much" related, but I just would like to remember my initial discussion about "communication channels" (#4316). We should start implementing not only the content but how we are going to deliver those messages.

**Comment by richtja** [comment]
> I agree with you @richtja. We need to revisit that. But I'm not sure if the first message ("started") should have all the keys.

True, maybe we can define types of messages based on their status and set requirements for each type of message.
> 
> I understand that is "not much" related, but I just would like to remember my initial discussion about "communication channels" (#4316). We should start implementing not only the content but how we are going to deliver those messages.

Agree

**Comment by beraldoleal** [comment]
@richtja I haven't thought about it much yet, but I like the idea of having class/objects by message types. This makes us follow some standards and not letting a simple JSON loosely being transmitted. On the other hand, having an open dict/json is easier for future improvements and portability. It is a trade-off:

Thinking about #4316 the way I thought was: Any component would emit an "event" within a channel/topic (lets say: 'avocado.job.task.started') and a payload (json when transmitting but parsed to a dict at the ends). The channel/topic has the "message type semantic".

As mentioned before, one of the advantages of having in a pub/sub model + websockets is that we could have very little code to implement runners in different languages.

So, if instead of having a generic "loose" payload we choose a fixed object/class with properties to "follow", we should keep in mind that would be nice to use other languages when transmitting those events. And by adopting the proposed model with pub/sub + websockets, a pure json would be used. And since the entire idea of pub/sub mechanism is to not send a message directly to nobody (there is no "runner - status server" direct communication) sticking with an object model seems strange here, IMO. 

So, having a restricted class/object with fixed properties depending on the type of the message could not be so easy to migrate a runner code to other languages. Because of that, I think I prefer having loose dict/json data as a payload instead of an object.

**Comment by richtja** [comment]
> @richtja I haven't thought about it much yet, but I like the idea of having class/objects by message types. This makes us follow some standards and not letting a simple JSON loosely being transmitted. On the other hand, having an open dict/json is easier for future improvements and portability. It is a trade-off:
> 
> Thinking about #4316 the way I thought was: Any component would emit an "event" within a channel/topic (lets say: 'avocado.job.task.started') and a payload (json when transmitting but parsed to a dict at the ends). The channel/topic has the "message type semantic".
> 
> As mentioned before, one of the advantages of having in a pub/sub model + websockets is that we could have very little code to implement runners in different languages.
> 
> So, if instead of having a generic "loose" payload we choose a fixed object/class with properties to "follow", we should keep in mind that would be nice to use other languages when transmitting those events. And by adopting the proposed model with pub/sub + websockets, a pure json would be used. And since the entire idea of pub/sub mechanism is to not send a message directly to nobody (there is no "runner - status server" direct communication) sticking with an object model seems strange here, IMO.

@beraldoleal Actually I am not proposing to use class/objects for messages on the runners side of communication I am proposing the standardization of communication. I want to define properties of each event or message payload, so the avocado can check if runner works correctly and will be able to react base on the message and their data. And developer of runner will know which message and which data have to send to give specific information to avocado.

Like when we want to log debug message from runner, runner will send debug message with properties time, message.type, message.log

> 
> So, having a restricted class/object with fixed properties depending on the type of the message could not be so easy to migrate a runner code to other languages. Because of that, I think I prefer having loose dict/json data as a payload instead of an object.

I agree that having a restricted class/object won't be easy to migrate a runner code to other languages, but I think that having just a strict standard for transmitted data won't be a problem.

**Comment by beraldoleal** [comment]
@richtja in this case I'm ok. Can you propose in a PR, affecting our documentation? Maybe on the contributor's guide, with details, and on "Test writers guide" with references to the contributor's guide. What do you think?

**Comment by richtja** [comment]
@beraldoleal Yes I can create PR with basics.
