### ISSUE TITLE
FAIL testcases from tearDown

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#4434]
As of today there is no way to `FAIL` a test from `tearDown`, since a `self.fail` from `tearDown` will result in a `ERROR`. 

```
    def tearDown(self):
        self.fail("Fails here")
```
which results in
```
ERROR: Fails here (14.24 s)
```
The current implementation limits the use of self.fail in `tearDown` and thus limiting usage of [dmesg](https://github.com/avocado-framework/avocado/blob/master/avocado/utils/dmesg.py) module in `tearDown`.

This is required in cases where we can probably check the failures with the dmesg as a post process for each test and based on that fail the test case. Hence we end up using the module in `test*` methods. While this is a workaround, few tests with multiple `test*` methods requires this step to be repeated for each test which becomes tedious.

So, is there a way to `FAIL` a test from tearDown ? If not, what is the best solution for this problem? 
Please post your thoughts on this. Thanks.

**Comment by harish-24** [comment]
Any update here would be helpful! Thanks.

**Comment by harish-24** [comment]
@clebergnu @beraldoleal @willianrampazzo Any pointers here please?

**Comment by beraldoleal** [comment]
@harish-24, sorry for the delay here.

My understanding (and I might be wrong) is that we are trying to isolate what is a "test failure" and what is a "bootstrap/cleanup failure" in order to avoid false positives. We have been discussing this for a long time, and it is a constant goal of our development to reduce those false-positives. If a test is flagged as "fail" we would like to make sure that this was during the test phase.

IMO, everything outside the test scope should be skip or error.

But, as I said, I might be missing something.

@clebergnu ?

**Comment by willianrampazzo** [comment]
> @harish-24, sorry for the delay here.
> 
> My understanding (and I might be wrong) is that we are trying to isolate what is a "test failure" and what is a "bootstrap/cleanup failure" in order to avoid false positives. We have been discussing this for a long time, and it is a constant goal of our development to reduce those false-positives. If a test is flagged as "fail" we would like to make sure that this was during the test phase.
> 
> IMO, everything outside the test scope should be skip or error.
> 
> But, as I said, I might be missing something.
> 
> @clebergnu ?

This is my understanding as well.

**Comment by clebergnu** [comment]
> @harish-24, sorry for the delay here.
> 
> My understanding (and I might be wrong) is that we are trying to isolate what is a "test failure" and what is a "bootstrap/cleanup failure" in order to avoid false positives. We have been discussing this for a long time, and it is a constant goal of our development to reduce those false-positives. If a test is flagged as "fail" we would like to make sure that this was during the test phase.
> 
> IMO, everything outside the test scope should be skip or error.
> 
> But, as I said, I might be missing something.
> 
> @clebergnu ?

That's right.  This is also along the lines for why `setUp()` is allowed to call `self.skip()` (because the test has not effectively started) but the test itself is only allowed to call `self.cancel()` (meaning that it ran, even if only partially).

Even Python's [unittest](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown) makes a distinction of what happens during the test method, and what happens at `tearDown()`.

I understand that the benefit of failing a test during `tearDown()` in your specific case is that it reduces boilerplate code, that is, you wouldn't need a line to check `dmesg` after the "body" of every test.  Is that right?

If so, that may be achieved via a custom decorator that runs the dmesg check, and depending on its result, changes the test outcome.  I'd suggest you use https://github.com/avocado-framework/avocado/blob/9ea1274f84ecc068b097ff44d51707b5743baa31/avocado/core/decorators.py#L21 as a starting point.

The end result can look like:

```python

from avocado import Test
from custom_decorator import fail_on_dmesg

@fail_on_dmesg
class MyTest(Test):

   def test(self):
      self.do_stuff()

   def test_2(self):
      self.do_other_stuff()

**Comment by harish-24** [comment]
> > @harish-24, sorry for the delay here.
> > My understanding (and I might be wrong) is that we are trying to isolate what is a "test failure" and what is a "bootstrap/cleanup failure" in order to avoid false positives. We have been discussing this for a long time, and it is a constant goal of our development to reduce those false-positives. If a test is flagged as "fail" we would like to make sure that this was during the test phase.
> > IMO, everything outside the test scope should be skip or error.
> > But, as I said, I might be missing something.
> > @clebergnu ?
> 
> That's right. This is also along the lines for why `setUp()` is allowed to call `self.skip()` (because the test has not effectively started) but the test itself is only allowed to call `self.cancel()` (meaning that it ran, even if only partially).
> 
> Even Python's [unittest](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown) makes a distinction of what happens during the test method, and what happens at `tearDown()`.
> 
> I understand that the benefit of failing a test during `tearDown()` in your specific case is that it reduces boilerplate code, that is, you wouldn't need a line to check `dmesg` after the "body" of every test. Is that right?
> 
> If so, that may be achieved via a custom decorator that runs the dmesg check, and depending on its result, changes the test outcome. I'd suggest you use
> 
> https://github.com/avocado-framework/avocado/blob/9ea1274f84ecc068b097ff44d51707b5743baa31/avocado/core/decorators.py#L21
> 
> as a starting point.
> The end result can look like:
> 
> ```python
> from avocado import Test
> from custom_decorator import fail_on_dmesg
> 
> @fail_on_dmesg
> class MyTest(Test):
> 
>    def test(self):
>       self.do_stuff()
> 
>    def test_2(self):
>       self.do_other_stuff()
> ```

@clebergnu Makes sense, will do that. Thank you for the pointers @clebergnu @beraldoleal @willianrampazzo. Closing the issue.

**Comment by harish-24** [comment]
@clebergnu Re-opening for slight clarity here. 

Does it make sense to add a `@avocado.fail_on_dmesg` class decorator which can be used by any Test classes and whose `test*` methods alone can be wrapped around with a decorator to FAIL based on dmesg failures.

If that is acceptable I can send in a PR with the something like
```
def fail_on_dmesg(cls):
    """
    Dmesg fail decorator

    Returns a class decorator used to signal the test when
    dmesg.DmesgError exception is raised.
    :param cls: Class to which failure is to be raised for test* methods.
    """
    behavior = 'fail'
    signal = core_exceptions.TestFail
    def raise_dmesg_fail(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            try:
                data = func(*args, **kwargs)
                dmesg.collect_errors_by_level()
                return data
            except dmesg.DmesgError as details:
                raise signal(repr(details)) from details
        return wrapper

    for key, value in list(vars(cls).items()):
        if callable(value) and value.__name__.startswith('test'):
            setattr(cls, key, raise_dmesg_fail(value))
    return cls
```
added to the `decorators.py`

If not, what would be the right place to have this?

**Comment by harish-24** [comment]
@clebergnu @beraldoleal @willianrampazzo Could you please help out with the previous comment?

**Comment by willianrampazzo** [comment]
I don´t see a problem with the implementation you proposed @harish-24, but I don´t think `decorators.py` is the best place. IMO, `utils/dmesg.py` would be a better place, but let's see what others think.

**Comment by beraldoleal** [comment]
@harish-24, IIUC, `dmesg.collect_errors_by_level()` uses a default `level_check=5`. Wich is being assumed by your decorator, that is removing that flexibility from Test Writers (let's say that a test writer would like to use your decorator with a different level_check? Based on your decorator, this would not be possible);

Besides that, I think that is valid to have decorators like this one, to help you with tests. Said that, I'm just not sure if `avocado/core/decorators.py` is the right place since there is supposed to have only "core decorators". (Imagine that every utility contributor decides to add a decorator there based on so many possible failures, can you see how big this file will be?).

So yes, maybe having this inside the utility module would be a better place, or even on your test side.

Now, we have for the next milestones a target to better organize our utility libraries (and plugins) repos. By having this better organization we could upgrade modules to packages, in order to have a specific `decorators.py` per utility library. IMO, that is something that we could improve soon.

**Comment by harish-24** [comment]
@willianrampazzo @beraldoleal Thanks for the inputs. So I will start with adding it to the dmesg utils library for now. Later we can decide on moving/organizing specific decorators per utility library once the milestone gets to a good shape.
