### ISSUE TITLE
avocado.conf Can't find

### ISSUE THREAD

**Issue by CDheyfeng** [avocado-framework/avocado#4548]
Hi，i need help.
i install avocado through pip,but can't find avocado.conf
![image](https://user-images.githubusercontent.com/29755181/116235139-10910200-a790-11eb-86d3-408cc912b345.png)

**Comment by beraldoleal** [comment]
Hi @CDheyfeng,

We have changed the way we process config options. Default values defined during the registration of the options (at source code), and because of that, an empty config file is now a valid option.

But, this command, shows the list of files that Avocado will process (in order) and you can start editing your own custom settings either on `avocado.conf` of your egg package or globally in your system.

`avocado config reference` command will show you all the possible options. You just need to split the section from the key. i.e: `sysinfo.collectibles.commands` will become:

```ini
[sysinfo.collectibles]
commands = /foo/bar/yourcommands
```

But, for sure we need to improve that on our documentation.

**Comment by CDheyfeng** [comment]
thanks，i got it  @beraldoleal
