### ISSUE TITLE
selftest/spell.sh: doesn't work as expected

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#4650]
I re-installed my development VM. After installing  git,  python-devel and gcc, I cloned the avocado repository and run:

`make requirements-selftests && make check`

This failed with:
```
....
RESULTS    : PASS 991 | ERROR 0 | FAIL 1 | SKIP 56 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ana/avocado/job-results/job-2021-06-07T14.34-054902e/results.html
JOB TIME   : 182.83 s
Failed tests:
check-902-selftests/spell.sh FAIL
make: *** [Makefile:120: check] Error 1

```
The output of` check-902-selftests/spell.sh/stderr`

```
Usage: pylint [options]

pylint: error: option --spelling-dict: invalid choice: 'en_US' (choose from '')

```

After some debugging this worked after I installed the package `enchant` (plus `hunspell` pulled as dependency), that comes from a different source package that `pyenchant`. 
At some moment, the test passed without enchant installed, but I haven't managed to reproduce this again.

The solution to this issue would be adding enchant to the list of dependencies to install at https://github.com/avocado-framework/avocado/blob/master/docs/source/guides/contributor/chapters/environment.rst  but I wanted to discuss first if this test is really worth it. It takes almost one minute and it's only checking for typos in the *.py files while the ones were the typos are more annoying are the documentation.

**Comment by willianrampazzo** [comment]
My 3 cents here (one for each comment):

- I think it is important to check the `py` files as the docstrings go to our documentation (see any of the links under `API Reference` on our documentation, like https://avocado-framework.readthedocs.io/en/latest/api/test/avocado.html).
- We should add spell check to the `docs` directory in addition to the `py` files, because, as you mentioned, they are also important.
- We should split static checks and run them just once in the CI. There is no reason to run them multiple times for each architecture (as you mentioned in one of our scrum meetings).

That being said, I'm all in for adding `enchant` to the dependencies as a starting point.

**Comment by beraldoleal** [comment]
I'm ok with adding enchant to the requirements.

**Comment by ana** [comment]
Thanks for all the interactions here, I have sent a PR to add enchant.
 I'll leave this issue open and we can revisit it in the future after we have improved `make check` and how the selftests are run.

**Comment by ana** [comment]
I'm closing this because after adding enchant to the documentation there is not a lot of more to do further than adding more spell checkers. I have added experimentally codespell at https://github.com/avocado-framework/avocado/pull/4918 
I have also opened a issue to not forget about the idea of running the static checks only once mentioned by @willianrampazzo
