### ISSUE TITLE
avocado 91.0 external runner fails with "Could not resolve references: ..."

### ISSUE THREAD

**Issue by sree314** [avocado-framework/avocado#4920]
It used to work with 90.0, but the switch to 91.0 changed the behaviour of external runner.

```
$ avocado run --external-runner ./extrun_io.sh generate
Could not resolve references: generate
```

Using `--test-runner=runner` works, so I suspect the `nrunner` change:

```
$ avocado run --test-runner=runner --external-runner ./extrun_io.sh generate
JOB ID     : e386e0b26192b487ae74b73857f0a5e56cab1f33
...
```
I just started using `avocado` so I'm not sure whether this means I need to change something to use external-runner or something broke.

**Comment by beraldoleal** [comment]
@sree314, two questions: Is your "extrun_io.sh" parsing the output somehow? Is "generate" a file or argument for "extrun_io.sh"?

**Comment by sree314** [comment]
Parsing the output of avocado? No.  

"generate" is an argument to `extrun_io.sh`. 

Depending on this argument, `extrun_io.sh` invokes `make` with different targets or external scripts.

I attach a simple script for testing (remove the .txt).
[extrun.sh.txt](https://github.com/avocado-framework/avocado/files/7085730/extrun.sh.txt)

Running this with 90.0:

```
$ avocado run --external-runner ./extrun.sh generate
JOB ID     : eb570c760e440b4cf4c1806b83e0574629ba05a3
JOB LOG    : $HOME/avocado/job-results/job-2021-08-31T13.23-eb570c7/job.log
 (1/1) generate: FAIL: Exited with status: '1', stdout: '', stderr: '' (0.05 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : $HOME/avocado/job-results/job-2021-08-31T13.23-eb570c7/results.html
JOB TIME   : 0.89 s
```

With 91.0:
```
$ avocado run --external-runner ./extrun.sh generate
Could not resolve references: generate
```

Notably, this doesn't seem to depend on the contents of the file:
```
$ avocado run --external-runner ./path/to/script/that/doesnt-exist generate
Could not resolve references: generate
```

**Comment by beraldoleal** [comment]
> Parsing the output of avocado? No.

No, I mean, parsing the output of the tests. But based on your example, I got it, you are just running and returning the exit code.

> 
> "generate" is an argument to `extrun_io.sh`.
> 
> Depending on this argument, `extrun_io.sh` invokes `make` with different targets or external scripts.

In theory you don't need an "external runner" using the new runner architecture, since your runner could be  `/bin/bash` or `./extrun.sh`.

However I found an issue while preparing a hintfile for you #4922 and I'm taking a look at this.

**Comment by beraldoleal** [comment]
Hi @sree314, I think you can use the concept of hintfiles + exec-test (since you have basically a shell script). Let me know if adding a `.avocado.hint` file in your execution path solves the issue:

```
# .avocado.hint
[kinds]
exec-test = ./extrun_io.sh

[exec-test]
uri = $testpath
args = generate
```

This will tell Avocado that ./extrun_io.sh is a test of type "exec-test" and will execute it with argument "generate".  And you can run normally, without arguments:

```
avocado run ./extrun_io.sh
```

The reason that we have `$testpath` variable here, is that you can declare multiple "tests" with regex. For instance:

```
[kinds]
exec-test = ./tests/*.sh

[exec-test]
uri = $testpath
args = generate
```

Please, let me know if that works and if we can close this issue.

**Comment by sree314** [comment]
I tried the hint files, but it doesn't behave the same as `--external-runner`. 

Given `avocado run --external-runner=./extrun_io.sh generate generate-tests build-tests`

it would run:

```
./extrun_io.sh generate
./extrun_io.sh generate-tests
./extrun_io.sh build-tests
```

The `exec-test` doesn't seem to have the same behaviour with `args`.

**Comment by beraldoleal** [comment]
Hi @sree314 , sorry for the late reply. I was on PTO last week.

Yes, it is not the same. With the Next Runner architecture, we are trying to keep things as simple as possible. And although it is easy creating new runners with this new architecture, it would be nice to understand the needs for it before starting implementing, otherwise, we can increase our learning curve for things that are supposed to be simple. 

So, what about using a wrapper script ? It that an option in this case?

###### generate.sh file:
```bash
#!/bin/bash
./extrun_io.sh generate
```

You would need 3 files, one for each argument.

This is what I can think right now for a "workaround", quick solution. But we can open a discussion about implementing this as a new runner, if really needed.

**Comment by sree314** [comment]
No issues, thank you for the reply!

I think I will transition to python-based tests instead of using scripts. I was only using scripts for legacy reasons, and this is as good a reason as any to move.

Please feel free to close the issue.

**Comment by beraldoleal** [comment]
@sree314 nice move! Thanks.

**Comment by willianrampazzo** [comment]
> No issues, thank you for the reply!
> 
> I think I will transition to python-based tests instead of using scripts. I was only using scripts for legacy reasons, and this is as good a reason as any to move.
> 
> Please feel free to close the issue.

hey, @sree314, sorry for the late message here, I thought about a solution for your problem after you mention you have access to change the script.

So, you can use the yaml to mux plugin and create a yaml file with the options you what to run. Those option will be passed as environment variables to your script. Here is an example:

```yaml
!mux
generate:
  OPTION: generate
generate-tests:
  OPTION: generate-tests
built-tests:
  OPTION: build-tests
```

This will require you handle the `$OPTION` environment variable inside your script, instead of the `stdin`. Here is a small change to the example you attached here:

```bash
#!/bin/bash

#if [ $# -lt 1 ]; then
#    echo "Usage: $0 generate|generate-tests|build-tests|run-tests|check-tests"
#    exit 1;
#fi;

set -e

case $OPTION in
    generate)
	false
	;;
    generate-tests)
	true
	;;
    build-tests)
	# leave compiling other tests to simple-test-runner
	false
	;;
    run-tests)
	true
	;;
    check-tests)
	true
	;;
    *)
	echo "Unrecognized option '$OPTION'"
	exit 1;
	;;
esac
```

To use it, call the `avocado` command with the `-m` option. Oh, if you need the tests to run sequentially, don't forget to set `--nrunner-max-parallel-tasks=1`. Here is the output:

```
$ avocado run --nrunner-max-parallel-tasks=1 -m extrun.yaml -- ./extrun.sh 
JOB ID     : 6daa90aa80751e80b5cfc7aadae41e152034da0a
JOB LOG    : /home/wrampazz/avocado/job-results/job-2021-09-16T15.34-6daa90a/job.log
 (1/3) ./extrun.sh;run-generate-0307: STARTED
 (1/3) ./extrun.sh;run-generate-0307: FAIL (0.01 s)
 (2/3) ./extrun.sh;run-generate-tests-ac14: STARTED
 (2/3) ./extrun.sh;run-generate-tests-ac14: PASS (0.01 s)
 (3/3) ./extrun.sh;run-built-tests-b2c5: STARTED
 (3/3) ./extrun.sh;run-built-tests-b2c5: FAIL (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2021-09-16T15.34-6daa90a/results.html
JOB TIME   : 2.00 s
```

You can find more information about the plugin here: https://avocado-framework.readthedocs.io/en/91.0/plugins/optional/varianter_yaml_to_mux.html

I hope it helps!

**Comment by beraldoleal** [comment]
FIY here: We hit the same issue today, with another user case. I just created #4980 so we can track a different alternative there.
