### ISSUE TITLE
Switch to Python f-strings

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5219]
Most of the strings are formatted with `.format()` or `'%'`, it would be great to use f-strings for string formatting when possible.

Pylint can help detecting the strings to update. Starting on version 2.11.0 it included a check `c0209: formatting a regular string which could be a f-string (consider-using-f-string)`.

[This link](https://miguendes.me/73-examples-to-help-you-master-pythons-f-strings) provides a good guide on how to update the strings.

**Comment by ozer550** [comment]
Hi there, I changed possible .format strings to f-strings but there were more than 100 instances of it, is there a way through which we can automate this process for %.

**Comment by ozer550** [comment]
Also, c0209 check was disabled is there any specific reason for it?

**Comment by richtja** [comment]
> Hi there, I changed possible .format strings to f-strings but there were more than 100 instances of it, is there a way through which we can automate this process for %.

Hi @ozer550 unfortunately I think there is no way how to automatize this process, and we need to go through the all instances. :confused:

> Also, c0209 check was disabled is there any specific reason for it?

This check is disabled,  because we are still using formatting a regular string and this will make our CI failing. When this issue will be solved, we can enable that check.

**Comment by al5929** [comment]
Hello! I can try to tackle this challenge.
I've followed the contribution procedures and got pylint working. I'll update the strings in accordance with C0209

**Comment by richtja** [comment]
Hi @al5929 and welcome to the avocado community, we will appreciate your contribution. Right now, there is PR #5267 from @ana about f-strings in `contrib` and `examples` directories. Also, there is draft #5266 from @ozer550 who is working on this issue right now, and I am not sure how far he is right now. So please coordinate your work with @ozer550. If you need any help, don't hesitate to ask, we will do our best to help you.

Because this is a huge refactoring, I can imagine splitting the work by `core`, `utils` and `plugins` packages, for easier coordination between contributors. @ozer550 what do you think?

**Comment by ana** [comment]
Hi @al5929 
As @richtja  mentioned, we're waiting to hear back from ozer550. This change can be made almost automatically , see https://github.com/avocado-framework/avocado/pull/5267 so there is little challenge. 
If you're interested to help and also learn, I can give you a more interesting task.

**Comment by al5929** [comment]
@richtja @ana 
Okay, I understand. I'm still pretty new to the whole contribution process, but I can definitely look into other issues.

**Comment by ozer550** [comment]
Currently I'm going through my exams so am unable to work with this PR so if you wanna work with it go ahead. I would love to split work so that it's not much work and we both can help together here.

**Comment by ana** [comment]
@al5929 @ozer550 I filed https://github.com/avocado-framework/avocado/issues/5270  that's more interesting for learning.
