### ISSUE TITLE
sysinfo subcommand should use local etc/avocado/* files

### ISSUE THREAD

**Issue by ruda** [avocado-framework/avocado#558]
When running avocado from the git sources, the `sysinfo` subcommand should use local (from the repository) `etc/avocado/*` files for it configuration, when the global `/etc/avocado` is not available. Otherwise the result will be not interesting.

Here's the transcription of my session:
```
$ ./scripts/avocado sysinfo
Commands configured by file: /etc/avocado/sysinfo/commands
Files configured by file: /etc/avocado/sysinfo/files
Profilers configured by file: /etc/avocado/sysinfo/profilers
Profilers declared: []
Profiler disabled: no profiler commands configured
System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])
Logged system information to /home/rmoura/Work/avocado/sysinfo-2015-04-17-10.36.37

$ ls -l /etc/avocado
ls: cannot access /etc/avocado: No such file or directory

$ find sysinfo-2015-04-17-10.36.37 
sysinfo-2015-04-17-10.36.37
sysinfo-2015-04-17-10.36.37/post
sysinfo-2015-04-17-10.36.37/post/added_packages
sysinfo-2015-04-17-10.36.37/profile
sysinfo-2015-04-17-10.36.37/removed_packages
sysinfo-2015-04-17-10.36.37/pre
sysinfo-2015-04-17-10.36.37/pre/installed_packages
```

**Comment by clebergnu** [comment]
Rudá, that's actually something that I mentioned during one of the meetings, prior to the code review.

My suggestion is that we shouldn't keep adding magic so that everything works from the source tree.

@lmr even mentioned that we should switch to running functional tests in a venv so that all this magic is unnecessary. I also mentioned this with @adereis yesterday and he also agreed with the reasoning.

**Comment by ruda** [comment]
OK, won't fix!
