### ISSUE TITLE
Podman spawner not compatible with non-core avocado runners

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5588]
**Describe the bug**
In #5577 we made changes into the way how podman spawner defines the runner command for running task. Unfortunately, this change is only compatible with core avocado runners like instrumented runner, but it removes the usage of non-core avocado runners like avocado-vt. The problem is that runners like avocado-vt use different namespace. See https://github.com/avocado-framework/avocado/pull/5577#discussion_r1086266317

**Additional information**
_Originally posted by @pevogam in https://github.com/avocado-framework/avocado/pull/5577#discussion_r1086266317_

**Comment by clebergnu** [comment]
Here's a proposal to address and make this feature more useful, in layers:

1. Expand the support to use *Python modules* as runners (as it's being done Today) with runners coming from outside of the `avocado.plugins.runners` namespace.  To do that, we can use the `pkg_resources` entrypoints.  One less obvious way, is to look for `console_scripts` entries matching `avocado-runner-{runnable.kind}`, and make sure they have a `main` attribute.  [This](https://github.com/avocado-framework/avocado-vt/blob/25ccd2beaf0fda8b1747643d9117b98d6c988620/setup.py#L58) would cover it for Avocado-VT.
2. Stop assuming that the runners on the "host" side, are the same as the ones in the container image.  To achieve that, it'd be necessary extra runs of the container to gather extra information, similarly to what is done Today wrt to Python versions.
3. For every runner, publish a location where the runner can be obtained.  This can also be done with `pkg_resources` AFAICT. So, instead of having that in the [Podman spawner itself](https://github.com/avocado-framework/avocado/blob/89ee80b894a55179756ca8f5b9047284cee9f496/avocado/plugins/spawners/podman.py#L152), and limited to the runners shipped in the `avocado-framework` egg, a pattern would specify where to get the egg that contains the runner.

How does that sound?

**Comment by pevogam** [comment]
I also updated the LXC spawner with this approach and seems to work very well, thanks @clebergnu for the pull request!
