### ISSUE TITLE
Unable to run single test using <test.py>:<test> format.

### ISSUE THREAD

**Issue by Geet2** [avocado-framework/avocado#5823]
**Describe the bug**
Unable to run single test using <test.py>:<test> format.

**Steps to reproduce**
1. Try to run single test from numactl.py from avocado-misc-tests

2. `avocado run --max-parallel-tasks=1 numactl.py:Numactl.test`   <<<< Bug
Current Behavior   : Runs all tests, 
Expected Behavior: Should run only one test

3. `avocado run --max-parallel-tasks=1 numactl.py:Numactl.test_interleave`   <<<< Works correct
Current Behavior   : Runs 1 test
Expected Behavior: Should run only one test

**System information (please complete the following information):**
 - OS: 6.6.0-1
 - Avocado version: Avocado 102.0
 - Avocado installation method: pip, rpm, github ? : github

**Comment by richtja** [comment]
Hi @Geet2, when I investigated this issue more deeply, I found out that this behavior is actually in connection with our [documentation](https://avocado-framework.readthedocs.io/en/latest/guides/user/chapters/concepts.html#test-references):
```
When the test references are about Instrumented Tests, Avocado will find any Instrumented test that starts with the reference, like a “wildcard”.
```

Because of this, I will close this issue, but feel free to reopen it if you will have any comments or questions.
