### ISSUE TITLE
jobdata doesn't store job configuration to file

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5857]
**Describe the bug**
Avocado jobdata should store avocado configuration to file for each avocado job. Unfortunately, this file is empty.

**Steps to reproduce**
$ avocado run examples/tests/passtest.py 
JOB ID     : 6303ea4fdf62ddfe92e324312862646175bd7f95
JOB LOG    : /home/janrichter/avocado/job-results/job-2024-01-19T17.52-6303ea4/job.log
 (1/1) examples/tests/passtest.py:PassTest.test: STARTED
 (1/1) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/janrichter/avocado/job-results/job-2024-01-19T17.52-6303ea4/results.html
JOB TIME   : 1.09 s

$ cat ~/avocado/job-results/latest/jobdata/config

**Expected behavior**
~/avocado/job-results/latest/jobdata/config file has avocado config in `ini` format.

**Comment by clebergnu** [comment]
This issue is indeed relevant, but with the work proposed in https://github.com/avocado-framework/avocado/pull/5859/commits/efc5edef8b3fe5e826764909400303bb95f7e69b it changes its expected outcome.

The proposed solution is to remove the config file, because of the existence of the (badly named) `args.json` file.
