### ISSUE TITLE
Skipping tests outside of Setup()

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#899]
Hi,

Currently, there is no way to call skip() outside of Setup().
Is there any design restriction in using it that way ?
There might be use cases for skipping individual.

--
Thanks
Narasimhan V

**Comment by ldoktor** [comment]
Dear Narasimhan, yes it was a design decision, quite hard one. The final decision is based on the test statuses definition:

http://avocado-framework.readthedocs.org/en/latest/ReferenceGuide.html#test-statuses

Extract from the discussion which IMO summarizes the decision is: _... but I agree that letting the test do it is a layer violation, since if the scope of the test already started, it's by definition not skipped anymore._

... this sentence was followed with __but__ and few reasons to allow it, but in the end we decided to restrict skip in tests, because it's not a good practice and people should learn not to use it.

**Comment by lmr** [comment]
@narasimhan14 yes, like @ldoktor said, it's a conscious design decision, and we argued quite a lot about it, and ultimately decided that the only place to skip a test is inside the setup method.

**Comment by narasimhan14** [comment]
@ldoktor @lmr is there any other way in avocado to specify certain tests only to run, or to skip certain tests, based on a condition ?

**Comment by lmr** [comment]
@narasimhan14 unfortunately we only planned for `skip`. Would it be good if we provided a decorator such as `unittest.skipIf` or something like that?

**Comment by narasimhan14** [comment]
@lmr would be great if its done

**Comment by lmr** [comment]
I've added a trello card for this:

https://trello.com/c/JK5Z5dql/526-add-a-decorator-to-skip-tests-similar-to-unittest-skip

I can't promise it'll be done quickly, but we'll do the best we can.

**Comment by clebergnu** [comment]
Since there's alredy a Trello card to track the implementation of something similar to `skipIf()`, I'm closing this issue to avoid duplicates.
